fossasia/open-event-attendee-android

app/src/main/res/layout/activity_login.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Login logo changed from FOSSASIA to eventyay

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/openevent/general/OpenEventGeneral.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginActivity.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginActivityViewModel.kt
app/src/main/java/org/fossasia/openevent/general/common/SingleLiveEvent.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/test/java/org/fossasia/openevent/general/DependencyTest.kt
build.gradle

feat: Add LoginActivity ViewModel

---

app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsRecyclerAdapter.kt

isolated components

---

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsRecyclerAdapter.kt

Smooth slide-up animation of Event Cards now occurs

---

README.md
app/src/main/res/values/strings.xml
scripts/update-apk.sh

Fixes #70 
apk should build correctly
corrected app name at other places too

fix : url corrected

---

app/src/main/res/layout/fragment_login.xml
app/src/main/res/layout/fragment_signup.xml

Fixes #49: Added in Layout the property to toggle password!
@iamareebjamal @nikit19

Fix#49 : Added for show or hide password

---

app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDao.kt
app/src/main/java/org/fossasia/openevent/general/event/EventService.kt

feat: Add events into database

---

app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt

fix: event url added in share

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
app/src/main/res/menu/event_details.xml
app/src/main/res/values/strings.xml

feat: Event can be stored directly in Calendar

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/social/SocialLink.kt
app/src/main/java/org/fossasia/openevent/general/social/SocialLinkApi.kt
app/src/main/java/org/fossasia/openevent/general/ticket/Ticket.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketApi.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketService.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt

*Added social-link model and api
*organised ticket files to a folder
#Fixes #96

Organised ticket files to a folder and added social-link api and model

---

app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragmentViewModel.kt
app/src/main/java/org/fossasia/openevent/general/auth/UserDao.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
build.gradle

feat : Add users into database

---

app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt

feat: Make search queries case insensitive

---

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt

fix: stop flickering of events on backpress

---

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt

Fix #103 : Get back to the same position of the recycler view 👍

Fixed Scrolling of Recycler View 

---

app/src/main/res/layout/content_event.xml

fix: make divide lines thicker and change colours

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/res/menu/event_details.xml
app/src/main/res/values/strings.xml

feat: allow users to report event

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt

remove recycler view animations

---

app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
app/src/main/res/layout/fragment_events.xml
app/src/main/res/values/strings.xml

feat: get events by location in home screen

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/1.json
app/src/main/java/org/fossasia/openevent/general/event/Event.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDao.kt
app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
app/src/main/res/drawable/ic_baseline_favorite_24px.xml
app/src/main/res/drawable/ic_baseline_favorite_border_24px.xml
app/src/main/res/layout/item_card_events.xml

add option to favourite event

---

app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt

fix: infinite progress bar bug

---

app/src/main/res/layout/content_event.xml
app/src/main/res/values/dimens.xml

fix: make event details UI same as before

---

app/src/main/java/org/fossasia/openevent/general/about/AboutEventActivity.kt
app/src/main/java/org/fossasia/openevent/general/about/AboutEventViewModel.kt
app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt

moved date format functions to EventUtils

---

app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/res/menu/profile.xml
app/src/main/res/values/strings.xml

feat: Add ticket issues link

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/res/drawable/ic_no_internet.xml
app/src/main/res/layout/content_no_internet.xml
app/src/main/res/layout/fragment_events.xml
app/src/main/res/values/strings.xml

 feat: show no internet card when there is no internet

---

app/src/main/java/org/fossasia/openevent/general/about/AboutEventActivity.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt
app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt

*moved showProgressBar functions to Utils 
*moved showCustomtab functions to Utils

feat: Add Utils file and move common function to Utils

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventTopic.kt
app/src/main/java/org/fossasia/openevent/general/event/EventTopicApi.kt
app/src/main/java/org/fossasia/openevent/general/event/EventTopicService.kt

feat: Add Event Topic model and API

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt

formatted date inside event details

---

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDao.kt
app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavouriteEventsViewModel.kt
app/src/main/res/layout/fragment_favorite.xml
app/src/main/res/layout/item_card_favorite_event.xml
app/src/main/res/menu/navigation.xml
app/src/main/res/values/strings.xml

feat: added favourites section

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/res/layout/content_event.xml

fix: Change title in EventDetailsFragment to Event name

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/1.json
app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
app/src/main/java/org/fossasia/openevent/general/attendees/Attendee.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeApi.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeDao.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketId.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketIdConverter.kt

feat: Add Attendee entity, API and DAO

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt

feat: save value of location from events fragment

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
app/src/main/res/drawable/border.xml
app/src/main/res/layout/content_event.xml
app/src/main/res/layout/fragment_tickets.xml
app/src/main/res/layout/item_ticket.xml
app/src/main/res/values/strings.xml

fixes #178 
Screenshots Updated

feat: make tickets screen

---

app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt

feat: Add option to favourite from search fragment

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/1.json
app/src/main/java/org/fossasia/openevent/general/ticket/Ticket.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt
app/src/main/res/layout/item_ticket.xml

feat: Add spinner for ticket quantity

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
app/src/main/res/drawable/ic_baseline_favorite_border_white_24px.xml
app/src/main/res/drawable/ic_baseline_favorite_white_24px.xml
app/src/main/res/menu/event_details.xml
app/src/main/res/values/strings.xml

feat: Add Favourite event option in Event Details Fragment action bar

---

app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragmentViewModel.kt

Change the toast which popped up on Sign up fail from "Unable to SignIn!" to "Unable to SignUp!"

Change SignIn to SignUp on sign up fail

---

app/src/main/AndroidManifest.xml

fix: hide bottom navigationView when keyboard pops up

---

app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/res/layout/item_card_favorite_event.xml

feat: Improve UI of search events

---

app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt

fix: Change root layout when clicked on a similar event

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/1.json
app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeId.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeIdConverter.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/order/Order.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDao.kt

feat: add order api,entity and dao

---

app/src/main/java/org/fossasia/openevent/general/AuthActivity.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt

fix: Profile fragment visible when logged out bug

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt
app/src/main/res/drawable/ic_baseline_event__black_24px.xml
app/src/main/res/drawable/ic_location_on_black_24dp.xml
app/src/main/res/layout/content_event.xml
app/src/main/res/layout/fragment_attendee.xml
app/src/main/res/layout/fragment_similar_events.xml
app/src/main/res/layout/fragment_social_links.xml
app/src/main/res/layout/item_social_link.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Fixes #221 #227 
*Added Organizer name and logo in Organizer section
*Resolved invisible attendee fragment issue
*Improved UI of EventDetailsFragment

feat: Improve UI of EventDetailsFragment

---

app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt

fix: set default value of qty to zero

---

app/src/main/java/org/fossasia/openevent/general/AuthActivity.kt
app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/res/menu/event_details.xml
app/src/main/res/menu/navigation.xml
app/src/main/res/menu/navigation_auth.xml
app/src/main/res/menu/profile.xml

fix: Remove Search menu viewing in toolbar in EventDetailsFragment

---

app/src/main/res/layout/fragment_signup.xml

The SignUp screen is now more clear to a new user in terms of what details to enter.

Change 'Username' hint to 'E-Mail' in fragment_signup.xml

---

app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
app/src/main/res/drawable/filled_border.xml
app/src/main/res/layout/fragment_tickets.xml
app/src/main/res/layout/item_ticket.xml

feat: Improve UI of Tickets Fragment

---

app/src/main/res/menu/event_details.xml

fix: Correct title of share item in Event details menu

---

app/src/main/java/org/fossasia/openevent/general/event/EventsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsViewModel.kt

feat: Exclude same event from Similar Events

---

app/src/main/res/layout/item_card_favorite_event.xml

fix: correct layout params for favorite event item

---

app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt

fix: Favorite FAB drawable bug

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt

feat: Allow User to select multiple tickets

---

app/src/main/res/layout/activity_about_event.xml

fix: fix UI of about activity

---

app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/res/drawable/ic_baseline_arrow_forward_24px.xml
app/src/main/res/layout/fragment_search.xml

feat: Add search FAB inside SearchFragment

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/1.json
app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/attendees/ListAttendeeIdConverter.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/order/Order.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketDao.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketService.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/res/layout/fragment_attendee.xml

feat : Add payments to the App

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt

fix: App crash on selecting register when not logged in

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchTimeActivity.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchTimeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
app/src/main/res/layout/activity_search_time.xml
app/src/main/res/layout/fragment_search.xml
app/src/main/res/values/strings.xml

feat: implement search by date

---

app/src/main/res/layout/item_card_similar_events.xml

fix: Fix similar event layout parameters

---

app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt

fix: fix crash in Search fragment

---

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt

feat: Reload events when retry option is clicked

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketDao.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketService.kt

feat: Hide payment options for free events

---

app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/res/layout/fragment_search.xml
app/src/main/res/values/strings.xml

fix: Add no search results message

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/res/layout/fragment_attendee.xml

First steps of #266 
Changes: Show ticket qty and amount.
Screenshot:

feat: add amount and quantity of tickets

---

app/src/main/java/org/fossasia/openevent/general/AuthActivity.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt

Fixes #291 
*Added entering and exiting animations
*Added a toast message for login alert

fix: add back button in auth activity

---

scripts/update-apk.sh

feat: add apks from master branch

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/1.json
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/ticket/Ticket.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketDao.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketService.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt

refactor: changed price type to float in ticket

---

app/src/main/java/org/fossasia/openevent/general/about/AboutEventActivity.kt
app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/res/layout/item_card_favorite_event.xml
app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt

fix UI and format date correctly of favorite item

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/order/Charge.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt

feat: add charge model and API

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeDao.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt

fix: Order eventId null bug

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/res/layout/fragment_attendee.xml

feat: integrate stripe

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketDao.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketService.kt
app/src/main/res/layout/fragment_attendee.xml
app/src/main/res/layout/item_ticket_details.xml
app/src/main/res/values/strings.xml

fixes #266 
Removed `if (it.toFloat() > 0)` from attendeeViewModel because for free orders the quantity was not calculated correctly.
Shifted nested scrollview to the top in attendee fragment
Hardcoded the currency to dollar for now as it is being worked upon in #316 
ScreenShot:

feat: show ticket amount details

---

app/src/main/res/layout/fragment_login.xml

fix: change username to email

---

app/src/main/res/layout/fragment_search.xml

fix: set default value of textView

---

app/src/main/res/layout/item_card_favorite_event.xml
app/src/main/res/values/dimens.xml

fix: Fix UI of search event items

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/res/layout/fragment_attendee.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

fixes #334 
Changes: More padding added to make it comparable with Eventbrite, Changed the accent color from pink to light blue, postal code and country added to the card object
Screenshot:

feat: create a custom form for stripe payments

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/1.json
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/order/Charge.kt
app/src/main/java/org/fossasia/openevent/general/order/Order.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt

feat: charge the user for the payment

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/settings.xml
build.gradle

feat: Add acknowledgements to settings

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/res/layout/fragment_attendee.xml
app/src/main/res/values/strings.xml

feat: add more details in attendee fragment

---

app/build.gradle
scripts/update-apk.sh

feat: add product flavor for fdroid

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedViewModel.kt
app/src/main/res/drawable/ic_baseline_calendar_24dp.xml
app/src/main/res/drawable/ic_baseline_tick_24dp.xml
app/src/main/res/layout/fragment_order.xml
app/src/main/res/menu/order_completed.xml
app/src/main/res/values/strings.xml

feat: add order completed screen

---

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginFragmentViewModel.kt

feat: Store user on logging in

---

LICENSE
README.md

chore: create license

---

app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt

refactor: corrected typo in ticketIdAndQty

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/order/ConfirmOrder.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt

feat: update order status to placed

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/res/layout/fragment_attendee.xml

feat: remove country for free events

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/order/Charge.kt
app/src/main/java/org/fossasia/openevent/general/paypal/CreatePaypalPaymentResponse.kt
app/src/main/java/org/fossasia/openevent/general/paypal/Paypal.kt
app/src/main/java/org/fossasia/openevent/general/paypal/PaypalApi.kt

feat: add paypal api and update charge entity

---

app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/res/layout/fragment_order.xml

fix: attendee fragment not reachable bug

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/1.json
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
app/src/main/res/layout/fragment_events.xml

feat: implement swipe to refresh

---

README.md

feat: Correct the README.md file of the project

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/1.json
app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/order/Order.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserVM.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersViewHolder.kt
app/src/main/res/drawable/ic_baseline_ticket_24dp.xml
app/src/main/res/layout/fragment_orders_under_user.xml
app/src/main/res/layout/item_card_order.xml
app/src/main/res/menu/navigation.xml

First steps of #293 
Screenshot:

feat: add my tickets fragment

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/1.json
app/src/main/java/org/fossasia/openevent/general/event/Event.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/res/drawable/ic_baseline_refund_24dp.xml
app/src/main/res/layout/content_event.xml
app/src/main/res/values/strings.xml

feat: add refund policy in event details

---

app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
app/src/main/res/layout/fragment_tickets.xml

feat: add no tickets message

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeApi.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeService.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt

feat:  delete attendees on order failure

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/1.json
app/src/main/java/org/fossasia/openevent/general/attendees/Attendee.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventApi.kt
app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersViewHolder.kt
app/src/main/res/layout/fragment_order_details.xml
app/src/main/res/layout/item_card_order_details.xml
app/src/main/res/values/strings.xml

fixes #403 and fixes #411 
Screenshot:

feat: add ticket details fragment

---

scripts/update-apk.sh

feat: update APKs of only corresponding branches when updated

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt

feat: take multiple attendees inside order

---

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragmentViewModel.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragmentViewModel.kt

fix: Show alert dialog whenever net connection is not present

---

app/src/main/res/layout/content_event.xml

fix: Fix the spacing between Location and Refund policy

---

app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt

fixes #416 
ease of access to the spinner now

feat: launch spinner on selecting order textView

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventApi.kt
app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserVM.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersViewHolder.kt
app/src/main/res/layout/item_card_order.xml

fix: show event info in my tickets

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/1.json
app/src/main/java/org/fossasia/openevent/general/auth/AuthApi.kt
app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/User.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/res/layout/fragment_edit_profile.xml
app/src/main/res/menu/profile.xml
app/src/main/res/values/strings.xml

feat: added edit profile fragment

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeApi.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeService.kt
app/src/main/java/org/fossasia/openevent/general/attendees/forms/CustomForm.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt

feat: Add custom form API and model

---

app/src/main/res/values/strings.xml

feat: change app name

---

app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
app/src/main/res/layout/item_card_order_details.xml
app/src/main/res/values/strings.xml

fixes #437 fixes #438 
Changes: added nested scrollview.
intent to open maps,calendar,event details
Screenshot:

feat: allow users to open calendar,maps and event details

---

app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserVM.kt

 fix: show correct no of tickets in order under user fragment

---

app/src/main/java/org/fossasia/openevent/general/auth/AuthHolder.kt

fix: Fix login error using another account after logging out

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/order/QrCode.kt
app/src/main/res/layout/item_card_order_details.xml

fixes #417 
SS after the changes

feat: added QR code in order detail fragment

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt

fix: update status to completed

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/res/values/strings.xml

feat: show tickets sold out dialog

---

README.md

update Readme: fix link to Espesso docs

---

app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserVM.kt

fix: wrong order identifier for tickets in orders under user fragment

---

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/main/res/layout/fragment_order.xml
app/src/main/res/values/strings.xml

feat: open MyTickets  from order completed fragment

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/openevent/general/auth/AuthApi.kt
app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt
app/src/main/java/org/fossasia/openevent/general/auth/ImageResponse.kt
app/src/main/java/org/fossasia/openevent/general/auth/UploadImage.kt

feat: allow user to change profile image

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt

feat: iterate over quantity of tickets while creating attendee

---

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt

fix: Fix the Title of Profile fragment after backpressing Edit Profile

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt

fix: show ticket details in attendee fragment

---

app/src/main/res/layout/item_card_order_details.xml

fix: add bottom margin in card

---

app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt

fix: Fix Tickets title after backpressing OrdersDetailsFragment

---

app/src/main/res/layout/fragment_profile.xml

fix: change profile fragment background colour

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
app/src/main/res/drawable/curved_border.xml
app/src/main/res/layout/fragment_attendee.xml
app/src/main/res/layout/item_attendee.xml

feat: allow user to enter multiple attendee details

---

app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt

feat: dont show ticket header and register while loading

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsRecyclerAdapter.kt
app/src/main/res/layout/item_attendee.xml

feat: create multiple attendees with different details

---

app/src/main/java/org/fossasia/openevent/general/AuthActivity.kt
app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt

feat: continue from attendee fragment when redirected to login

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserVM.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersViewHolder.kt
app/src/main/res/layout/item_card_order.xml

 feat: Show "See N tickets" line in Tickets in OrdersUnderUserFragment 

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
app/src/main/res/layout/fragment_attendee.xml

 feat: dont display multiple attendee details recycler for single ticket

---

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt

fix: deal with vector graphic profile placeholder picture for API < 20

---

app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragmentViewModel.kt

fix: make Unable to SignUp error message more informative

---

app/build.gradle
app/proguard-rules.pro

fix: fix signing bug

---

app/build.gradle

chore: update version code

---

scripts/update-apk.sh

fix: duplicate APKs bug in APK branch

---

README.md

Docs: Added App links to README.md

---

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt

fix: Hide soft keyboard when LOGIN button is pressed

---

app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt

fix: Remove profile fragment after logout

---

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt

feat: Direct to profile section when edit profile successful

---

app/src/main/res/layout/activity_auth.xml

fix : Color mismatch in bottom navigation bar in login/signup activity

---

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt

fix: hide soft keyboard when forgot password is pressed

---

app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt

fix: correct the title on rotation

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt

fix: ticket fragment shown twice bug

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt

chore: use different base urls for debug and release apks

---

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt

fix: App exit on back pressed

---

app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/res/menu/profile.xml

Fixes #663
Changes: 
The value of showAsAction has been changed from always to ifRoom|collapseActionView

Search text comes once.

---

app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt

Fixes #664
Changes:  FavoriteFragment.kt

fix: Set empty message when unlike event from favorites

---

app/src/main/res/layout/fragment_signup.xml

fix: align progress bar of signUp fragment

---

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt

fix: Clear activity from back stack after authentication and logout

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/openevent/general/SearchResultsActivity.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
app/src/main/res/layout/activity_search_results.xml
app/src/main/res/layout/fragment_search.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

feat: Open search results in new activity

---

app/src/main/java/org/fossasia/openevent/general/SearchResultsActivity.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
app/src/main/res/layout/activity_search_results.xml
app/src/main/res/layout/placeholder_item_card_search.xml

feat: Add shimmer effect in search results activity

---

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt

Fixes #681, typo, and extra parentheses
Before and after:
</p>

fix: Open saved state for Events

---

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt

fix: Handle configuration changes for MainActivity

---

app/src/main/res/layout/activity_search_results.xml

fix: Add search shimmer layout inside ScrollView 

---

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/res/menu/profile.xml
app/src/main/res/menu/search.xml

fix: Split menus in respective fragments

---

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt

fix: Set attendee fragment on root layout (#770)

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/SearchResultsActivity.kt
app/src/main/java/org/fossasia/openevent/general/about/AboutEventActivity.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpViewModel.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt
app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/utils/HttpErrors.kt
app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt
app/src/main/java/org/fossasia/openevent/general/utils/extensions/LiveDataExtensions.kt

- Add KTX goodness
- Remove some linting errors
Partial fix of #783

chore: Make some LiveData observers non-null

---

app/src/main/res/layout/fragment_login.xml
app/src/main/res/layout/fragment_orders_under_user.xml
app/src/main/res/layout/fragment_profile.xml

Fix #789
Some layouts are changed to coordinator layout, required for #788

chore: change to coordinator layout 

---

app/src/main/java/org/fossasia/openevent/general/event/EventsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsRecyclerAdapter.kt

fix: Set scaleType programmatically for floating action buttons

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/navigation/navigation_graph.xml

Part of #822 
Fixes #780 
Fixes #760
Fixes #726 
Fixes #719

feat: Add navigation architecture component for MainActivity fragments

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt

fix: Handle title if error fetching event

---

app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt

fix: #820 
changed the isVisible parameter of progess bar from true to parameter passed by liveData

fix: progress bar doesn't go away even after tickets are being load in orderUnderUserFragment  

---

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/navigation/navigation_graph.xml

feat: Handle all root layout fragments with navigation architecture

---

app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchTimeActivity.kt
app/src/main/res/drawable/ic_checked.xml
app/src/main/res/layout/activity_search_time.xml

Fixes #805
Changes: 
Font changed.
CheckTextView used instead
Logic implemented so that the current choice is checked,
@nikit19 @iamareebjamal Do review

feat: Improve UI of Search Time Activity

---

app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt

fix: Perform search in onCreate() at start

---

app/src/main/res/layout/fragment_signup.xml

fix: UI misalignment in login fragment

---

app/src/fdroid/java/org/fossasia/openevent/general/search/GeoLocationUI.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
app/src/main/res/layout/fragment_search_location.xml
app/src/main/res/navigation/navigation_graph.xml
app/src/playStore/java/org/fossasia/openevent/general/search/GeoLocationUI.kt

feat: Remove search location activity with fragment using navigation

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/res/layout/fragment_attendee.xml

fix: toast to snackbar for attendee fragment

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
app/src/main/res/layout/fragment_event.xml
app/src/main/res/layout/fragment_events.xml
app/src/main/res/layout/fragment_similar_events.xml

fix: toast to snackbar for events related fragments

---

app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
app/src/main/res/layout/fragment_order.xml
app/src/main/res/layout/fragment_order_details.xml

fix: toast to snackbar for search result and order related fragments

---

app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt

fix: Show soft keyboard as view specific

---

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt
app/src/main/res/anim/slide_down.xml
app/src/main/res/anim/slide_up.xml

feat: Add animations to bottom navigation drawer

---

app/src/main/res/layout/fragment_signup.xml

Fixes #895
Changes: Remove grey background color from sign up fragment layout

fix: change signup fragment color to white

---

app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt

feat: add animations to transitions

---

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
app/src/main/java/org/fossasia/openevent/general/WelcomeFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchLocationViewModel.kt
app/src/main/res/layout/fragment_welcome.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

feat: Polish implementation for welcome fragment

---

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
app/src/main/res/values/strings.xml

fix: welcome back snackbar and remove hardcoded strings

---

app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/res/layout/fragment_events.xml
app/src/main/res/layout/fragment_signup.xml

fix: position of snackbar for error in fetching events

---

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt

fix: Snackbar displaying message twice in login fragment

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Fixes #933
Changes: Updated the android gradle plugin to 3.3.0

chore: updated the Android Gradle plugin to 3.3.0 (#933)

---

app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserVM.kt

fix: Handle progress for no internet in tickets

---

app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt

fix: use navigation arch to redirect to events when logout 

---

app/src/main/res/layout/fragment_about_event.xml

fix: UI misalignment due to about event fragment

---

app/src/main/java/org/fossasia/openevent/general/auth/SignUpViewModel.kt

changed the contains function string for snackbar Message logic in accordance with the server response
fixed : #979

fix: Wrong snack-bar message appearing

---

app/build.gradle
app/src/fdroid/java/org/fossasia/openevent/general/search/SmartAuthViewModel.kt
app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/playStore/java/org/fossasia/openevent/general/search/SmartAuthViewModel.kt

feat: Integrate app with google smart lock

---

app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt

fix: Disable save state of search view to resolve CastException

---

app/src/main/res/layout/fragment_search_time.xml

added scroll view as a parent to all the CheckedTextView
fix: #1012

fix: not all option are available in search time fragment in landscape mode

---

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt

fix: redirect to events after login

---

app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt

changed the order of setting values for mutableProgressTickets and mutableProgressTickets in loadTicket function in ticketViewModel
fix: #1023
screen shot

fix: disabling the register button in ticket Detail

---

app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/main/res/layout/fragment_order.xml

Fixes #495 
Changes: Replaced FAB with ImageButton and removed elevation. Also removed redundant line defining ScaleType in OrderCompletedFragment.kt which has already been defined in layout file fragment_order.xml.

fix: Replaced FAB with ImageButton and removed elevation.

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/res/layout/fragment_attendee.xml

Fixes #865 
Changes: Added check for invalid email address in attendee details.

fix: Invalid Email address gets taken in in Attendee Details.

---

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt

Fixes #606 
Changes:ActionBar and Bottom Navigation bar hidden

fix: Forgot screen Screen Full Size

---

app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt

removed the on destroy method from orderDetailFragment
fix: #1069

fix: Ticket title is appearing when going to event detail from order detail

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt

Fixes #256 
Changes: Stopped re fetching of similar events and organization details on setting favorite.

fix: Social Links and Similar Events get refetched when event is favorited

---

app/src/playStore/java/org/fossasia/openevent/general/search/LocationServiceImpl.kt

Fixes #1089 
Changes: The magic number has been replaced with a variable.

fix: Remove magic number.

---

README.md

Fixes #1112 
Changes: A small grammatical mistake in README.md has been fixed.

docs: Add missing parenthesis

---

app/src/main/res/layout/fragment_welcome.xml

Fixes #1113 
Changes: Changes in UI of Splash Screen(Image size and Text size increased)
Before:-
After:

fix: Improvement in Welcome Screen

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/res/layout/fragment_attendee.xml

Fixes #1031 
Changes: User will be able to add ticket only after checking the terms and conditions box.

feat: Checkbox for terms and conditions

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt

Fixes #1024 
Changes:Added a count of how many attendee details are invalid, and send a snackbar message only for the first non valid attendee.

fix: multiple snackbars in attendee details

---

app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/res/layout/fragment_favorite.xml

Fixes #690 
Changes: Added a GoTo button in Likes Fragment to direct the user to Search Fragment.

feat: Added GoTo button in Likes Fragment

---

app/src/main/res/layout-land/item_card_order_details.xml
app/src/main/res/layout/item_card_order_details.xml
app/src/main/res/values/strings.xml
build.gradle

I added landscape mode for the ticket order.
Before:
After

feat: Added landscape mode for order #1155

---

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt

Reverts fossasia/open-event-android#1152

Revert "fix: After coming back from result detail, search result come back to the top, not current position #1150"

---

app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/settings.xml

Fixes #190 
Changes: Added legal section in settingsFragment.

feat: Add legal section

---

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt

fix: Pop to back fragment after authentication

---

README.md

Fixes #1166 
Changes: Corrected the error

chore: Fix typos in README

---

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpViewModel.kt
app/src/main/res/layout/fragment_login.xml
app/src/main/res/layout/fragment_signup.xml
app/src/main/res/values/styles.xml

Fixes #594 
Changes: Disabled login and signup buttons until all inputs are correct. Also made confirmpassword in signup red when confirmpassword is not same as password entered.

feat: Disable signup and login button.

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt

Details: Changed add() new similarEventFragment to the fragment by replace new similarEventFragment when rotating
Fixes #1186 
Changes:
It doesn't create the bug anymore

fix: another layer of SimilarEvents created 

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
app/src/main/res/layout/content_event.xml

Fixes #756 
Fixes #1132 
Changes: Replaced googlemap with mapbox.

fix: Replace google map with mapbox.

---

app/src/main/res/layout-land/item_card_order_details.xml
app/src/main/res/layout/item_card_events.xml
app/src/main/res/layout/item_card_favorite_event.xml
app/src/main/res/layout/item_card_order.xml
app/src/main/res/layout/item_card_order_details.xml
app/src/main/res/layout/item_card_similar_events.xml
app/src/main/res/layout/placeholder_item_card_events.xml
app/src/main/res/layout/placeholder_item_card_search.xml

Fixes #1195 
Changes: 
Card views would now have ripple effect.

feat: Ripple effect in cards

---

app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt

feat: Store credentials with Google smart lock after authentication

---

app/src/main/java/org/fossasia/openevent/general/about/AboutEventFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchTimeFragment.kt
app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketIdAndQtyWrapper.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/res/navigation/navigation_graph.xml

Fixes #1205 
Changes: Replaced existing fragment args with safe args. Default values
nullability has been inferred by me based on what values were being
passed earlier.

refactor: Migrate entire project to use Safe Args

---

app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
app/src/main/res/layout/fragment_signup.xml
app/src/main/res/values/strings.xml

Detail:
Added invalid message in sign up fragment when an email is invalid + extract some string
Fixes #1178

fix: Added displaying invalid message on email

---

app/src/main/res/layout-land/fragment_welcome.xml
app/src/main/res/layout-land/item_card_order_details.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/content_event.xml
app/src/main/res/layout/fragment_attendee.xml
app/src/main/res/layout/fragment_edit_profile.xml
app/src/main/res/layout/fragment_favorite.xml
app/src/main/res/layout/fragment_login.xml
app/src/main/res/layout/fragment_order.xml
app/src/main/res/layout/fragment_search.xml
app/src/main/res/layout/fragment_tickets.xml
app/src/main/res/layout/item_card_events.xml
app/src/main/res/layout/item_card_favorite_event.xml
app/src/main/res/layout/item_card_order.xml
app/src/main/res/layout/item_card_order_details.xml
app/src/main/res/layout/item_card_similar_events.xml
app/src/main/res/layout/item_ticket.xml
app/src/main/res/layout/item_ticket_details.xml
app/src/main/res/layout/placeholder_item_card_events.xml
app/src/main/res/values/dimens.xml

Fixes #1246 
Changes:Removed the hardcoded margins/strings

fix: Removed HardCoded Margins

---

app/src/main/res/values/styles.xml

Fixes #1249 
Changes: Changed the colors.

fix: wrong colors in Buttons in Login/Signup Fragment

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt

Fixes #1264 
Changes: Added different Card for payments.

fix: Added More CardType during Payment

---

app/src/main/res/values-bn-rIN/strings.xml

Fixes #1274 
Changes: Made the App compatible with Bengali language.

feat: Added Bengali Translations.

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/res/layout/fragment_attendee.xml
app/src/main/res/values-bn-rIN/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings-country-name.xml
app/src/main/res/values/strings.xml

Details:
I added the names of countries into an array-string file and then create a spinner to pick the country name
Fixes #1287 

feat: Added Country Picker Dialog

---

app/build.gradle

Fixes #1359
Changes: 
Disabled lint check for missing translations.

chore: Disable missing translation lint check

---

app/src/main/res/layout/content_no_internet.xml

feat: Add ripple effect for RETRY

---

app/src/main/res/layout/content_event.xml

Fixes #1354 
Changes: 
Placed TimingLayout below evenOrganizerName
Change HardCoded_dimens to use dimen_resources

fix: ImproperPlacement of OrganizerName

---

app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
app/src/main/res/values-bn-rIN/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/settings.xml

Fixes #1268 
Changes: Now website can be seen.

feat: Option to see Website

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt

Fixes #1389 
Changes: Replaced context.let with requireContext() in SettingsFragment

fix: Improve Kotlin Code

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
app/src/main/res/layout-land/item_card_order_details.xml
app/src/main/res/layout/item_card_order_details.xml
app/src/main/res/values/strings.xml

Fixes #1338 
Changes: Added Download Button to download tickets both landscape and portrait
Screenshots for the change:![screenshot-1553118209746](https://user-images.githubusercontent.com/29139786/54721185-50379980-4b87-11e9-8a89-3050e7696d68.jpg)

feat: Download tickets as pdf

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/res/layout/content_fetching_event_error.xml
app/src/main/res/layout/fragment_event.xml
app/src/main/res/values-bn-rIN/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings.xml

Fixes #1366 
Changes: new layout file for error on fetching event 

fix: Content for Error fetching event (#1366)

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt

Fixes #1429 
Changes: Improved the Alert Dialog buttons UI.
Before:
After:

fix: Dialog Buttons

---

app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
app/src/main/res/drawable/round_button.xml
app/src/main/res/layout/fragment_favorite.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Fixes #1430 
Changes: Made UI simillar to Eventbrite with the search option as in Eventbrite.

feat: Make empty favorite fragment similar to Eventbrite.

---

app/src/main/res/layout/content_no_internet.xml
app/src/main/res/values/colors.xml

Fixes #1435 
Changes: Changed Button to Material Component Button.
Issue is fixed.
Before:
After:

fix: Fixed Button Color

---

app/src/main/res/layout/placeholder_item_card_tickets.xml
app/src/main/res/values/dimens.xml

Fixes #1419 
Changes: Now shimmer is visible perfectly

fix: Fixed Shimmer Layout Issue

---

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt

Fixes #1460 
Changes: Fixed FAB issue in Edit Profile.

fix: Fixed FAB issue in Edit Profile

---

app/src/main/java/org/fossasia/openevent/general/about/AboutEventViewModel.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt

Fixes #1467 
Changes: Used Lambdas in a more concise way.

fix: Concise Lambdas 

---

app/src/main/java/org/fossasia/openevent/general/common/RecyclerViewCallbacks.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
app/src/main/res/layout/content_event.xml

Fixes #139 
Changes: Add Event Image Transitions

feat: Add shared element transition

---

app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt

fix: Handle action bar visibility in search location fragment

---

app/build.gradle

chore: Bump version code and change version name

---

app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
app/src/main/res/color/text_color_chip_state_list.xml
app/src/main/res/layout/fragment_search_results.xml
app/src/main/res/values/styles.xml

Fixes #1517 
Changes: Added Chips in searchResultFragment

feat: add chips for search

---

app/src/main/res/values-hi-rIN/strings.xml

Fixes #1275 
Changes: Added Hindi Translations to the app.

feat: Added Hindi Translations

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/2.json
app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt

Fixes #1538 
The database is upgraded into version 2. I tested by checking out to old commits, build that APK and then check out to the latest APK to update. Everything seems to work fine now.

fix: upgrade app database to version 2

---

app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/res/layout/fragment_favorite.xml

Details:
Add horizontal views on Favorite Fragment to improve current view
Fixes: #1493

fix: Improve horizontal likes fragment

---

app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/res/layout/fragment_favorite.xml

Fixes: #1563 
Changes:
- Improved layout of FavoriteFragment
- Refactored a couple of views
Previous layout
New layout

fix: improve favorite fragment layout

---

app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt

Fixes #1569 
Changes: Added code for back button to work.

fix: Make back button in searchtypefragment work.

---

app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchLocationViewModel.kt
app/src/main/res/layout/fragment_search_location.xml
app/src/main/res/layout/placeholder_item_event_location.xml

Fixes #1585
Changes: Add shimmer while loading event locations

feat: display shimmer while loading event locations

---

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt

fix: crash on login fragment

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt

Fixes #1603 
Changes: convert null string to empty string

fix: convert null description to empty description

---

app/src/main/java/org/fossasia/openevent/general/auth/AuthApi.kt
app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/change/ChangeRequestToken.kt
app/src/main/java/org/fossasia/openevent/general/auth/change/ChangeRequestTokenResponse.kt
app/src/main/java/org/fossasia/openevent/general/auth/change/Password.kt
app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
app/src/main/java/org/fossasia/openevent/general/settings/SettingsViewModel.kt
app/src/main/res/layout/dialog_change_password.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/settings.xml

Fixes #1355 
Changes: Added option to change password in settings.

feat: Add option to change password.

---

app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt

Fixes #1579 
Changes: Added logout dialog when account is clicked in settings fragment.

feat: Add log out dialog in settings fragment.

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt
app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt

Fixes #1509
Changes: Move API calls from onCreateView to onCreate

fix: Unnecessary calls for social links and similar events

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/res/layout/content_event.xml
app/src/main/res/layout/item_speaker.xml

Changes: Made speaker's recyclerview horizontal and changes items to cards.

feat: Changed speaker item layout and made rv horizontal.

---

app/src/main/java/org/fossasia/openevent/general/speakers/Speaker.kt
app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerViewHolder.kt

Fixes #1627 
Changes: Removed html tags.

fix: Remove html tags from speaker's bio.

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt

Fixes #1664 
Changes:  disable api logs for release build

fix: Disable API logs for release build

---

app/src/main/java/org/fossasia/openevent/general/common/RecyclerViewCallbacks.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/speakers/Speaker.kt
app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerApi.kt
app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerDao.kt
app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerFragment.kt
app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerService.kt
app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerViewModel.kt
app/src/main/res/layout/fragment_speaker.xml
app/src/main/res/navigation/navigation_graph.xml

Fixes #1629 
Changes: Added speaker fragment. Let me know if UI needs any changes.

feat: Add speaker fragment

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchTypeAdapter.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchTypeViewModel.kt
app/src/main/res/layout/fragment_search_type.xml

Add no-internet card on SearchTypeFragment
Fixes: #1582

fix: Add no-internet card on SearchTypeFragment

---

app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
app/src/main/res/layout/fragment_search_filter.xml
app/src/main/res/navigation/navigation_graph.xml
app/src/main/res/values/strings.xml

Fixes #1666 
Changes: Added Sort By Name, Date Filters in SearchFiltersFragment

feat: Add Sort By Filters

---

app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchTypeViewModel.kt
app/src/main/res/layout/fragment_search_type.xml
app/src/main/res/layout/placeholder_item_event_type.xml

Fixes: #1573
Changes:
Add shimmer while loading event types

feat: display shimmer while loading event types

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorsDetailAdapter.kt
app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorsFragment.kt
app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorsViewModel.kt
app/src/main/res/layout/content_event.xml
app/src/main/res/layout/fragment_sponsors.xml
app/src/main/res/layout/item_sponsor_detail.xml
app/src/main/res/navigation/navigation_graph.xml
app/src/main/res/values/strings.xml

feat: Add sponsors section to show details of all sponsor

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
app/src/main/java/org/fossasia/openevent/general/sessions/Microlocation.kt
app/src/main/java/org/fossasia/openevent/general/sessions/Session.kt
app/src/main/java/org/fossasia/openevent/general/sessions/SessionApi.kt
app/src/main/java/org/fossasia/openevent/general/sessions/SessionRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/sessions/SessionType.kt
app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewHolder.kt
app/src/main/res/layout/content_event.xml
app/src/main/res/layout/item_session.xml

Fixes #1646 
Changes: Added Session Sections along with micro-location and session-type

feat: Add Session Sections

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/about/AboutEventViewModel.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpViewModel.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/event/faq/EventFAQViewModel.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedViewModel.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchLocationViewModel.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchTypeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
app/src/main/java/org/fossasia/openevent/general/settings/SettingsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt
app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerViewModel.kt
app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/utils/extensions/RxExtensions.kt
app/src/playStore/java/org/fossasia/openevent/general/search/GeoLocationViewModel.kt
app/src/playStore/java/org/fossasia/openevent/general/welcome/WelcomeViewModel.kt

Fixes #1696 
Changes: Refractor entire project to use RxExtensions

chore: refractor to use RxExtensions

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/utils/DataBindingAdapters.kt
app/src/main/res/layout/content_event.xml
app/src/main/res/layout/fragment_event.xml

refactor: refactor to use data binding

---

app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt
app/src/main/res/layout-land/item_card_order_details.xml
app/src/main/res/layout/item_card_order_details.xml
app/src/main/res/menu/order_detail.xml
app/src/main/res/values/strings.xml

Detail:
- Create a bitmap from container view of single ticket
- Turn bitmap into an URL and then share it to another app
Fixes: #1353

feat: Add sharing ticket feature

---

app/src/fdroid/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchTimeFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/res/navigation/navigation_graph.xml

Fixes #1614 
Changes: Refractor app to navigation global actions

 refactor: refactor to use navigation ACTIONS API

---

app/build.gradle

chore: Bump version code and name for release v0.2.1

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/4.json
app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
app/src/main/res/navigation/navigation_graph.xml

Detail:
- Because SimilarEventFragment is inside EventDetailFragment, when calling navController, the current destination is EventDetailFragment, not SimilarEventFragment.
- Update database schema 4.json
Fixes: #1715 , update databas schema #1714 

fix: app crash on navigating Similar Event Detail

---

app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
app/src/main/res/navigation/navigation_graph.xml

fix: Reloading events onBackPressed after search

---

app/src/main/res/navigation/navigation_graph.xml

fix: Remove overlapping animation conflicts

---

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
app/src/main/res/values/strings.xml

Detail:
- Update user photo by default image (encoded)
Fixes: #1017

feat: Add delete user photo feature

---

app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
app/src/main/java/org/fossasia/openevent/general/settings/SettingsViewModel.kt

feat: Update google smart lock with new updated password

---

app/build.gradle

feat: Add LeakCanary for debug implementation

---

app/src/main/java/org/fossasia/openevent/general/search/PlaceSuggestionsAdapter.kt
build.gradle
gradle/wrapper/gradle-wrapper.properties

chore: bump gradle from 3.3.2 to 3.4.1

---

app/build.gradle
app/schemas/org.fossasia.openevent.general.OpenEventDatabase/5.json
app/src/fdroid/java/org/fossasia/openevent/general/di/FlavorSpecificModules.kt
app/src/fdroid/java/org/fossasia/openevent/general/search/GeoLocationViewModel.kt
app/src/main/java/org/fossasia/openevent/general/OpenEventGeneral.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
app/src/playStore/java/org/fossasia/openevent/general/di/FlavorSpecificModules.kt
app/src/test/java/org/fossasia/openevent/general/DependencyTest.kt

Details:
- Fix imports
- Remove Scope
- Fix build by improving database schema
@iamareebjamal There is a part of the dependency test where there is no dryRun() function anymore. I don't know how to fix that so, for now, I'm commenting it out

chore: Bump Koin 1.0.2 to version 2.0.0-GA4

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt
app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewModel.kt
app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerApi.kt
app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerService.kt
app/src/main/res/layout/fragment_session.xml
app/src/main/res/navigation/navigation_graph.xml
app/src/main/res/values/strings.xml

Detail:
- Set up recycler/adapter to fetch speakers under session
Fixes: #1786

feat: Add speakers under session

---

app/src/main/res/navigation/navigation_graph.xml
app/src/playStore/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt

fix: Add crashed on selecting location from welcome fragment

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt

fix: Retrieve stripe api key from build config

---

app/src/main/res/color/navigation_item.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/values/dimens.xml

Fixes #1787
- Before - 
</p>
- After - 
</p>

fix(ui): Profile fragment and Navigation

---

app/src/fdroid/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
app/src/main/res/layout-land/fragment_welcome.xml
app/src/main/res/layout/fragment_events.xml
app/src/main/res/layout/fragment_welcome.xml
app/src/main/res/values/strings.xml
app/src/playStore/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt

Details:
- Add skip button in WelcomeFragment to move to EventsFragment directly
Fixes: #1817 

feat: Add skip button

---

app/src/main/res/layout/fragment_search_filter.xml

fix: Make search filter fragment scrollable

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/codeofconduct/ConductCodeFragment.kt
app/src/main/res/layout/fragment_conduct_code.xml
app/src/main/res/menu/event_details.xml
app/src/main/res/navigation/navigation_graph.xml
app/src/main/res/values/strings.xml

Details:
- Set up code of conduct fragment
Fixes #1836

feat: Add code of conduct

---

app/src/main/res/layout/fragment_orders_under_user.xml

Fixes #1836 
- Make shimmer scrollable

fix(ui): Order under user fragment

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/order/Order.kt
app/src/main/res/layout/fragment_attendee.xml
app/src/main/res/values/strings.xml

Details:
- Set up billing information section to take company information
- Set up checkbox to see whether the billing information is needed
Fixes: #1849

feat: Add billing information section

---

app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
app/src/main/res/layout/fragment_search_filter.xml
app/src/main/res/navigation/navigation_graph.xml
app/src/main/res/values/strings.xml

feat: Add filter for sessions and speakers

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt

fix: App crashes on registering free tickets

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt

Details:
- Use constant string for payment mode
- Add payment mode for offline payment + place order with PLACED status
Fixes: #1858

fix: Add payment mode

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
app/src/main/res/layout/fragment_attendee.xml
app/src/main/res/values/strings.xml

Fixes #1861 
- Use the same process for single and multiple tickets
</p>

fix: Ticket registration form

---

app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedViewModel.kt
app/src/main/res/layout/fragment_order_completed.xml
app/src/main/res/layout/placeholder_item_card_similar_events.xml
app/src/main/res/navigation/navigation_graph.xml

feat: Set up similar events in order completed fragment

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/6.json
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/event/Event.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/res/drawable/border_background_ticket_timer.xml
app/src/main/res/layout/fragment_attendee.xml
app/src/main/res/navigation/navigation_graph.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Details:
- Add time counter on ordering ticket
- Add dialog on cancel ordering ticket
Fixes: #1776

feat: Add time counter on ordering ticket

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt

feat: Set ticket buyer details non editable

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt

fix: Order cancel alert dialog

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/OpenEventGeneral.kt
app/src/test/java/org/fossasia/openevent/general/DependencyTest.kt

chore(deps): Bump koin_version to 2.0.1

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt

fix: Handle progress in event details fragment

---

app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUp.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpViewModel.kt
app/src/main/res/layout/fragment_auth.xml
app/src/main/res/layout/fragment_signup.xml
app/src/main/res/navigation/navigation_graph.xml

Details:
- Check invalid email
- Set up pop back to AuthFragment when changing email like Eventbrite
- Remove unnecessary variable in SignUpFragment
Fixes: #1898

fix: invalid email in AuthFragment

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt

fix: Update progress on error in event details

---

app/src/main/java/org/fossasia/openevent/general/auth/AuthApi.kt
app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt
app/src/main/java/org/fossasia/openevent/general/auth/ResendVerificationEmailResponse.kt
app/src/main/res/drawable/ic_tick_inside_circle.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/values/strings.xml

feat: Add profile verification

---

app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
app/src/main/res/layout-land/item_card_order_details.xml
app/src/main/res/layout/fragment_order_details.xml
app/src/main/res/layout/item_card_order_details.xml
app/src/main/res/values-land/dimens.xml
app/src/main/res/values/dimens.xml

Fixes #1874 
Fixes #1907 
</p>

fix: Ticket/order detail UI

---

app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/main/res/navigation/navigation_graph.xml

fix: Order completed to events navigation

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt

chore: Bump preference from alpha01 to beta01 and fix errors

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerApi.kt
app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerService.kt

Display only:
- featured speakers
- accepted sessions
- public call for speaker
Fixes: #1897

fix: Display valid information about sessions, speakers, call for speakers

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/6.json
app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt
app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
app/src/main/java/org/fossasia/openevent/general/feedback/Feedback.kt
app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackApi.kt
app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackDao.kt
app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackFragment.kt
app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackService.kt
app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/feedback/FeedbackViewModel.kt
app/src/main/res/layout/content_event.xml
app/src/main/res/layout/fragment_feedback.xml
app/src/main/res/layout/item_feedback.xml
app/src/main/res/navigation/navigation_graph.xml
app/src/main/res/values/strings.xml

Details:
- Add FeedbackFragment for multiple feedback
- Add border for feedback item view
- Show only 2 feedback in the main EventDetailsFragment and the rest in FeedbackFragment
Fixes: #1929

feat: Improve Feedback section

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt

fix: Multiple crashes in event details due to app link data

---

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
app/src/main/res/layout/content_event.xml
app/src/main/res/navigation/navigation_graph.xml
app/src/main/res/values/strings.xml

feat: Display tag for already registered tickets

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/order/invoice/DownloadInvoiceService.kt
app/src/main/res/menu/order_detail.xml
app/src/main/res/values/strings.xml

feat: Set up downloading invoice 

---

app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt

fix: Shimmer layout is overlapping tickets

---

app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
app/src/main/res/values/strings.xml

fix: Blank order details fragment

---

app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerWithEventDao.kt
app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorWithEventDao.kt
app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorsDetailAdapter.kt

Detail:
- Make the right SQL query
- Add index for column
Fixes: #1784

fix: Database declaration warning by Travis build

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsListAdapter.kt
app/src/main/java/org/fossasia/openevent/general/event/similarevent/SimilarEventViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/event/similarevent/SimilarEventsListAdapter.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
app/src/main/java/org/fossasia/openevent/general/utils/DataBindingAdapters.kt
app/src/main/res/layout-land/item_card_order_details.xml
app/src/main/res/layout/item_card_events.xml
app/src/main/res/layout/item_card_favorite_event.xml
app/src/main/res/layout/item_card_order.xml
app/src/main/res/layout/item_card_order_details.xml
app/src/main/res/layout/item_card_similar_events.xml

Details:
- Set up data binding to RecyclerView/Adapter
- Separate different layout with different ViewHolder/Adapter
Fixes: #1709

feat: Add data binding to recycler/adapter

---

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
app/src/main/res/layout/fragment_events.xml
app/src/main/res/values/strings.xml

Fixes #1953 
- Overlapping of UI
- Displacement of layouts
</p>

fix: Events fragment UI

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/event/similarevent/SimilarEventViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt

Details:
- Share event by URL
- Remove unused methods
Fixes: #1962 

fix: sharing event by URL

---

app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt

fix: Check for device location settings

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/res/layout/fragment_attendee.xml
app/src/main/res/values/strings.xml

Details:
- Remove unused methods
- Add sign out/log in in AttendeeFragment
Fixes: #1965 

feat: Add signout/login while ordering ticket

---

app/src/main/java/org/fossasia/openevent/general/search/LocationAdapter.kt
app/src/main/java/org/fossasia/openevent/general/search/LocationViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchLocationViewModel.kt
app/src/main/res/layout/fragment_search_location.xml
app/src/main/res/layout/item_location_text.xml
app/src/main/res/values/strings.xml

Details:
- Save recent search location by Preference
- Improve UI in SearchLocationFragment
- I set up RecyclerView instead of ListView as I found problem allowing nestedScrollView enabled with ListView, which made ListView only showing the first item
Fixes: #575

feat: Add recent search query

---

app/src/fdroid/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
app/src/main/res/layout/fragment_auth.xml
app/src/main/res/navigation/navigation_graph.xml
app/src/main/res/values/strings.xml
app/src/playStore/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt

feat: Ask for login/sign up at start

---

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt
app/src/main/java/org/fossasia/openevent/general/utils/extensions/ViewExt.kt
app/src/main/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt
app/src/main/res/layout/fragment_events.xml
app/src/main/res/layout/fragment_favorite.xml
app/src/main/res/layout/fragment_orders_under_user.xml

Details:
- Add toolbar when scrolling in fragments
- Add animation to show and hide toolbar
Fixes: #1951 

feat: Add toolbar for fragments + animation

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/auth/RequestAuthenticator.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt

chore(deps): Bump logging-interceptor to 4.0.0 and fix errors

---

app/src/main/res/drawable/background_fragment_search.xml
app/src/main/res/layout/fragment_search.xml

fix: Fix distorted image

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallFragment.kt
app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallViewModel.kt
app/src/main/res/layout/fragment_search_results.xml

Details:
- Previously, SpeakersCall icon from EventDetailsFragment sometimes disappear
- Speakers are not updated in SpeakersCallFragment after getting some updates from EditSpeakerFragment
- Add toolbar elevation in SearchResultsFragment
- Remove unused methods
Fixes: #1997

fix: Reloading SpeakersCall and Speakers

---

app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt
app/src/main/java/org/fossasia/openevent/general/utils/DataBindingAdapters.kt
app/src/main/res/layout/item_card_order.xml
app/src/main/res/values/colors.xml

Details:
- Add placed and pending order in ordersUnderUserFragment
- Add tag for orders
Fixes: #2027 

feat: Add placed and pending order

---

app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationFragment.kt

fix: Back button in location fragment

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedViewModel.kt

Fixes #2043
Changes: Removed redundant code

fix: redundant code after zip

---

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
app/src/main/res/navigation/navigation_graph.xml

fix: App crashes on first time sign in

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
app/src/main/res/layout/content_event.xml

Details:
- Add shimmer and progress bar for indicating loading
- Improve the code by extracting methods
Fixes: #2053

feat: Add loading indicator in EventDetailsFragment

---

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
app/src/main/res/layout/fragment_events.xml

Details:
- Retain events in EventsFragment after screen rotation or going back from EventDetailsFragment
Fixes: #2052

fix: Retain events in EventsFragment

---

app/src/main/java/org/fossasia/openevent/general/data/Resource.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
app/src/main/java/org/fossasia/openevent/general/utils/DataBindingAdapters.kt
app/src/main/res/drawable/border_order_status.xml
app/src/main/res/layout/item_card_order.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

fix: truncated order status

---

app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationFragment.kt
app/src/main/res/layout/fragment_search_location.xml

Details:
- Use EditText instead of SearchView
Tested in API 22, 26,28
Fixes: #2085

fix: SearchLocationFragment back press not working

---

app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
app/src/main/res/values/strings.xml

fix: Use event's time zone as default

---

app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/EventTopicApi.kt

fix: Add upcoming filter for similar events

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
app/src/main/res/layout/fragment_attendee.xml
app/src/main/res/navigation/navigation_graph.xml

fix: Make billing information compulsory for paid orders

---

app/src/main/res/values/strings-country-name.xml

fix: Sort country code and country name

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/8.json
app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt
app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/Event.kt
app/src/main/java/org/fossasia/openevent/general/event/EventApi.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDao.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/event/topic/EventTopicApi.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEvent.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventApi.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsViewModel.kt
app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedViewModel.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchResultsViewModel.kt
app/src/main/res/layout/dialog_login_to_like.xml
app/src/main/res/navigation/navigation_graph.xml
app/src/main/res/values/strings.xml

Details:
- Set up API request to add/delete favorite event
- Fetch favorite event from server
Fixes: #1652 

feat: Add log in to save favorite event

---

app/src/main/res/layout/dialog_feedback.xml
app/src/main/res/layout/fragment_search_location.xml

fix: Location icon and feedback dialog

---

app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationFragment.kt

fix: Empty search location

---

.travis.yml

chore: Fix travis build

---

app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt

fix: Stop progress on error in tickets

---

app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt

fix: Empty UI in order completed fragment

---

app/src/main/java/org/fossasia/openevent/general/search/type/SearchTypeFragment.kt

fix: Array list in search type fragment

---

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt

feat: Open external ticket URL

---

app/src/main/java/org/fossasia/openevent/general/speakercall/EditSpeakerFragment.kt
app/src/main/res/navigation/navigation_graph.xml

feat: Add edit/remove/take image for speaker profile photo

---

app/src/main/java/org/fossasia/openevent/general/about/AboutEventFragment.kt
app/src/main/java/org/fossasia/openevent/general/notification/NotificationsViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt
app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerFragment.kt
app/src/main/res/layout/fragment_about_event.xml
app/src/main/res/layout/fragment_session.xml
app/src/main/res/layout/fragment_speaker.xml

Details:
- Improve code
- Add autolink to text to redirect to website for web url, mailing app for email text
Fixes: #2187

feat: Add autolink to text

---

app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt

fix: Included tax for tickets

---

app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
app/src/main/res/values/strings.xml

Details:
- Check totalAmount in order to set "Order Now", "Register" for button
- Get tickets detail saved from ViewModel instead of fetching from the database
Fixes: #2238

fix: Change Order Now/Register Button in TicketsFragment

---

app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt

fix: Number format exception for donation amount

---

app/src/main/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt

fix: Location in welcome fragment

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt

fix: Change button text to "REGISTER" for offline payment options

---

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt

Details:
- Make new profile image taken editable by saving userAvatar
Fixes: #2201

fix: New profile image editable

---

app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt

Details:
- Disable options to pick donation ticket quantity when no donation is entered
Fixes: #2243 

fix: Prevent no donation

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/9.json
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/speakercall/EditSpeakerFragment.kt
app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallProposalFragment.kt
app/src/main/java/org/fossasia/openevent/general/utils/StringUtils.kt
app/src/main/res/layout/fragment_attendee.xml

Details:
- Check all invalid fields and show errors on all fields
Fixes: #2239

fix: Improve invalid fields

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt

fix: Email and URL validation

---

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt

Details:
- Add Pay Now button based on the payment method
Fixes: #2258

fix: Add Pay Now button based on payment method

---

app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt

feat: Add ticket currency for ticket detail

---

app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/settings.xml

fix: policy URL links

---

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt

fix: Hide notification Icon when user is not logged in

---

app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
app/src/main/java/org/fossasia/openevent/general/notification/NotificationsViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt
app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewHolder.kt

fix: Invalid event's timezone for sessions

---

app/src/main/res/layout-land/item_card_order_details.xml

fix: Add missing text view in Item Card Detail

---

app/src/main/java/org/fossasia/openevent/general/order/OrderDataSource.kt

fix: tickets expired at wrong time

---

app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
app/src/main/res/layout/fragment_order_details.xml
app/src/main/res/layout/item_card_order_details.xml

fix: Remove unnecessary code to centralize ticket details
Fixes: #2293
**Screenshots**

fix(ui): Align ticket details in center

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/9.json
app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDao.kt
app/src/main/java/org/fossasia/openevent/general/order/ExpiredOrderFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/Order.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDao.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDataSource.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderDataSourceFactory.kt
app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
app/src/main/res/layout/fragment_expired_order.xml
app/src/main/res/layout/fragment_orders_under_user.xml

Fixes: #2205
**Screenshots**
**Related Context**
Work left: Fetch attendees and save to database when fetching order (https://github.com/fossasia/open-event-attendee-android/issues/2299)

feat: Save tickets to DB

---

fastlane/metadata/android/en-US/full_description.txt
fastlane/metadata/android/en-US/short_description.txt

Part of #2314 
According to https://docs.fastlane.tools/getting-started/android/setup/

chore: Update description for fastlane metadata

---

CONTRIBUTING.md
README.md

chore: Update README and CONTRIBUTING guidelines

---

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/9.json
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
app/src/main/java/org/fossasia/openevent/general/order/Order.kt
app/src/main/res/layout/fragment_attendee.xml

feat: Add State Information for Order

---

scripts/update-apk.sh

Fixes #2376 
Changes: 
- updated script

chore: dry run on dev to master merge pr

---

README.md

Fixes #2393 
Changes: updated Travis ci badges to custom names

chore: update travis ci badges

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/ExpiredOrderFragment.kt
app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationFragment.kt
app/src/main/java/org/fossasia/openevent/general/search/type/SearchTypeFragment.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
app/src/main/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt

chore(deps): bump lifecycle_version from 2.2.0-beta01 to 2.2.0-rc01

---

app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt

Fixes #2417 
Changes: Handled the observer for the result

fix: App crash on search results fragment

---

app/build.gradle
app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt

Fixes #2420  
Fixes #2415 
Changes: Bump the version of stripe-android from 12.2.0 to 12.3.0 and fixed build errors

chore(deps): bump stripe-android from 12.2.0 to 12.3.0

---

app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt
app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt

Fixes #2216 
Changes: Removed unused/unnecessary variables from TicketsViewModel.

fix: Add prices in for all tickets in TicketIdAndQty

---

app/src/main/res/layout/fragment_orders_under_user.xml

Fixes #2413 
Changes: Changed the layout margin of noTicketsScreen layout.

fix: UI conflict in ticket section

---

scripts/update-apk.sh

fix: avoid directory switching when running fastlane

---

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt
app/src/main/res/layout/fragment_login.xml
app/src/main/res/values/strings.xml

Fixes #2476 
Changes:  Updated the message displayed to user in case of error. Removed the verifyMessage function.

fix: Resolve reset password mail UI issue

---

app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt

Fixes #2487 Move search result observer to onCreateView

fix: Move search result observer to onCreateView

---

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt

fix: Remove listener after navigating from auth screen

---

app/src/main/res/values-ur-rPK/strings.xml

added strings.xml file in values for urdu language support
Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
fixes issue no 2535 

chore: Add support for urdu language
