fossasia/open-event-attendee-android

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt, app/src/main/res/layout/fragment_profile.xml, app/src/main/res/menu/profile.xml, app/src/main/res/values/strings.xml
First steps of #27 
Manage events opens the organizer's app if it is installed or else opens up the organizer's app in playstore.
Shifted log out to menu.
=> feat: add menu for managing events and log out

app/build.gradle, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
fixes #159 
Now events can be loaded automatically when the user opens the app
=> feat: save location name in a shared preference

app/src/main/java/org/fossasia/openevent/general/about/AboutEventActivity.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/res/layout/content_event.xml, app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt
fixes #240 #210 
changes: format date correctly and show the date and time in a different format if the start and end date are same
Screenshots:
=> fix: format date and time correctly everywhere

app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt, app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragmentViewModel.kt
fixes #326 
After this : We dont need to open profile fragment to load user into database so that attendee details are automatically loaded on selecting tickets
=> feat: store user profile on sign up or login

app/src/main/res/layout/fragment_attendee.xml
fixes #409 #376 
before fix : 
after fix :
=> fix: events recycler visible in attendee fragment bug

app/src/main/java/org/fossasia/openevent/general/OpenEventGeneral.kt
Sorry, if I did it not correctly; doing it first time; please, let me know what was wrong.
When extended from Application the app failed to open both on emulator with KitKat 4.4.2 (API 19) and on my physical device. As I replaced Application with MultiDexApplication it started opening OK.
=> fix: extend OpenEventGeneral from MultiDexApplication (#442)

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt
=> feat: Resume from my tickets after LOGIN

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt, app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt
=> fix: Load user details in Edit Profile section

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
=> feat: retain fragments while switching

app/src/main/res/layout/activity_search_location.xml
=> fix: Capitalize first letter of words in search

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
Fixes #653 
Changes: Added logic to load the user's profile avatar in the EditProfileFragment.
=> fix: User avatar not loading in EditProfileFragment

.travis.yml, build.gradle
This is a fix for unsupported gradle version error in Android Studio. Switching to Gradle v3.2.1 resolves this error, but causes the Travis CI builds to fail because the current travis.yml file does not allow support for build tools v28. Therefore, travis.yml file has also been modified to accept build tools v28.
Fixes #659 
Changes: 
1. Project level build.gradle file to use Gradle v3.2.1
2. .travis.yml file to allow build tools v28.
=> chore: Switch to Gradle 3.2.1 and support for build tools v28 to travis

app/build.gradle, build.gradle
Fixes #648 
Changes: Upgrade support library, compileSdkVersion & targetSdkVersion to recent 28.
Add few android.support libraries because it must use same version specification. (Mixing versions can lead to runtime crashes).
=> chore: Upgrade support library to recent 28

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
Fixes #631
Changes: MainActivity.kt
=> fix: App stuck when open event from favorites

app/build.gradle
Fixes #662 
Fixes #675 
Changes: build.gradle(app)
=> chore: Degrade Android support library to 27

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
Fixes #683 
Changes: Added code to check if the profile picture URL is not empty, as Picasso requires a non-empty url. Thus if there is no profile picture initially, there should be no attempt to load such an image.
=> fix : App crash while trying to editing a profile with no profile picture

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt, app/src/main/res/values/strings.xml
Changed Toast notification text to " Welcome back ! " From " success ".
Fixes #697
=> chore: Toast notification text for successful login

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
Fixes #686 
Changes: MainActivity.kt
=> fix: improve logic of onBackPressed for Fragments

app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
Fixes #714 
Changes: 
Now the toolbar title will be 'Events' instead of the wrongly displayed title 'Profile'.
=> fix: Display correct toolbar title on going back from Settings fragment

app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
Fixes #644
Changes: Set search fragment without the saved state.
=> fix: Text overlapping in search fragment

app/src/main/java/org/fossasia/openevent/general/AuthActivity.kt, app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt
Fixes #689
Changes: MainActivity, AuthActivity, and utility class
=> refactor: Move load fragments logic to Utils

README.md
Fixes #720
Changes: use the official fdroid badge in readme and remove the app links since clicking on the badge anyway leads the user to the respective app stores.
=> fix: use the official fdroid badge in readme

CONTRIBUTING.md, README.md
Fixes #729 
Changes: There is a section for First Time Contributors to read the ContributionHelp.md but there is no such file. I have added the file and created the required link in README.md
README.md: Before, without link
README.md: After, with link
ContributionHelp.md: New file
=> docs: Add CONTRIBUTING.md file link it to README.md

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/openevent/general/MainActivity.kt
Fixes #738 Rotating screen anywhere opens Tickets fragment 
**Changes:**
Now the fragment would not change to Tickets fragment when the screen is rotated.
**GIF for the change:**
=> fix: Handle fragment transaction correctly on rotation

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt
Fixes #752 
Changes: 
Changed names of the instances of the ViewModel classes in SignupFragment and LoginFragment in the auth package along with all the usages of the variable i.e. refactored the name of the variables.
=> fix: Change instance names of ViewModel for Signup & Login fragments

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt, app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/SignUpViewModel.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt, app/src/main/java/org/fossasia/openevent/general/settings/SettingsViewModel.kt
Fixes #754 
Changes: The ViewModel classes,their created instances and all their usages have been refactored according to convention by removing the term "Fragment" from them. The ViewModels changed:
attendeeFragmentViewModel -> attendeeViewModel (instances only)
ProfileFragmentViewModel -> ProfileViewModel (class and instances)
LoginFragmentViewModel -> LoginViewModel (class and instances)
ProfileFragmentViewModel -> ProfileViewModel (class and instances)
SignUpFragmentViewModel -> SignUpViewModel (class and instances)
SettingsFragmentViewModel -> SettingsViewModel (class only)
=> fix: Refactor ViewModels and their instances across the project

app/src/main/res/layout/fragment_orders_under_user.xml
Fixes #757 
Changes: 
Now ProgressBar will show in the middle of the screen instead of the top in Tickets.
=> fix: Shift ProgressBar in Tickets to middle of screen

app/build.gradle, app/proguard-rules.pro
=> chore: Update retrofit and okhttp-interceptor

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
Fixes #744
Earlier it is tanking value from 2nd initialization but after chore updates, it acts as variable form first initialization which is always null due to 2nd value is not effective.
=> fix: Variable ticketIdAndQty initialized twice

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt
Fixes #770 
Fixes #791 
Authenticate user by startActivityForResult and handle result in the attendee fragment. No need to start new main activity, set the fragment and get bundles.
=> fix: Authenticate user by start activity for results in attendee section

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt, app/src/main/res/layout/fragment_login.xml, app/src/main/res/layout/fragment_orders_under_user.xml, app/src/main/res/layout/fragment_profile.xml
Part for  #785 
fix #797
merge after #790
Screenshots for Login fragment UI fix
GIF for the Snackbar change:
=> fix: toast to snackbar for login work

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt, app/src/main/res/values/strings.xml
- Partial #786 
- Fixes #792 
- Open fragment after authentication
=> refactor: Attendee fragment (#786) (#792)

app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt, app/src/main/res/layout/fragment_signup.xml
=> fix: toast to snackbar for signup work 

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
Fixes #808
Changes: Corrections in the Terms of Service sentence (add space between words, color correction in privacy policy).
=> fix: Correction in Attendee Details (Terms of Service)

app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
programitically setting the scale type of share button of fragment_order fragment
fixes: #807
=> fix: Misalignment of share image in order fragment

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchLocationActivity.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTimeFragment.kt, app/src/main/res/layout/fragment_search_time.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/playStore/java/org/fossasia/openevent/general/search/GeoLocationUI.kt
=> feat: Remove search time activity with fragment using navigation

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt, app/src/main/res/anim/fade_in.xml, app/src/main/res/anim/fade_out.xml, app/src/main/res/anim/slide_in_left.xml, app/src/main/res/anim/slide_in_right.xml, app/src/main/res/anim/slide_out_left.xml, app/src/main/res/anim/slide_out_right.xml
=> feat: Add animations to fragments

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/res/layout/activity_main.xml
Fixes #869 
Changes: 
The snackbar is now visible above the bottom navigation view
=> fix: Reposition sign in canceled Snackbar

app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt
=> fix: use navigation arch to redirect to Events

app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt
Fixes #924 
Changes: 
Replaces slide animations with fade animations for login and signup fragments.
=> fix: two different anims for switching between login/signup

app/src/main/res/layout/fragment_profile.xml
Fixes #936 
Changes:
Replace deprecated constant "fill_parent" with "match_parent" in fragment_profile.xml
=> chore: replace fill_parent with match_parent in fragment_profile

app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt, app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt
Fixes #928, #922 
Changes: Keyboard pops up automatically when the search location fragment is opened. Hence the user can start typing straight away instead of first tapping "where". Now if the back press is tapped once, the keyboard goes down and when the back press is tapped again, the user is sent back to the main activity.
=> fix: Keyboard shows up automatically when search location fragment opens.

app/src/main/res/layout/fragment_tickets.xml
Fixes #957
Changes: 
Added `android:fillViewport="true"` in scrollview in tickets fragment which pushes the snackbar to the bottom of the screen.
=> fix: Snackbar issue fixed in tickets fragment

app/src/main/res/layout/fragment_event.xml, app/src/main/res/layout/fragment_social_links.xml
fix #962   Snackbar is appearing in the middle of the screen in eventDetailFragment 
removed the coordinate layout from fragment_social_links
added app:layout_dodgeInsetEdges="bottom" top frameLayout of fragment_event so whole thing shifts up when snackbar is shown
fix #962
=> fix: Snackbar is appearing in the middle of the screen in eventDetailFragment

app/src/main/res/layout/fragment_similar_events.xml
fixed: #981 Similar event fragment not displaying correctly
adding a linear-layout as a parent to the fragment
fixes: #981 
Screenshot
=> fix: #981 Similar event fragment not displaying correctly

app/src/main/res/layout/fragment_edit_profile.xml
fixed :#986 wrong placement of snackbar in edit profile segment
removed padding from parent coordinateLayout and added to child linearLayout
fix : #986
=> fix: wrong placement of snackbar in edit profile segment

app/src/main/res/layout/fragment_tickets.xml
changed the parent element from ScrollView to NestedScrollView in ticket_fragment
added android:descendantFocusability="blocksDescendants" property to get the scroll position to top every time orientation changed
fixed: #988
=> fix: all tickets are not showing in ticket-fragment in landscape mode

app/src/main/res/layout/content_event.xml
Fixes #1000
Changes: 
Change placeholder image from "background" to "src" so that scaleType is applicable for the image
=> fix: stretched out event placeholder image

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/EventService.kt, app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt, app/src/main/res/layout/fragment_favorite.xml
Fixes #1007
Changes: 
Changed the spelling of "favourite" to "favorite" in 38 occurences over 14 files. This includes refactoring variables & classes and their instances.
=> fix: consistent spelling of 'favorite'

app/src/main/res/layout/fragment_search.xml
removed the extra parent linear-layout, removed the top margin give the parent linear-layout gravity centre and also layout_gravity centre
fix: #960 #931
=> fix: Search view getting overflowed out of the screen

app/src/main/java/org/fossasia/openevent/general/about/AboutEventFragment.kt
fixed: #1018 back button disappear after orientation change in about fragment #
set the setDisplayHomeAsUpEnable property to true of supportActionBar
fix: #1018
=> fix: back button disappear after orientation change in about fragment 

app/src/main/res/navigation/navigation_graph.xml
fixes #1032 
Changes: Added layout previews for the Navigation Editor. Earlier, the layout previews were absent. This change will make it quicker for people to get an overall idea about the screens present in the app.
=> chore: enable layout previews in Navigation editor

app/build.gradle, app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTimeFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTimeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values/strings.xml, build.gradle
Fixes #997  
Fixes #998
Fixes #1047
=> feat: Remove all explicit intents and use safe args for search date

app/src/main/res/layout/fragment_search_location.xml, app/src/main/res/values/strings.xml
Make the hint which appears in the location text field more
polite/professional. Vertically centre the "Use my current location"
button text with respect to the button icon.
Fixes #1056 
Changes: Make the hint which appears in the location text field more polite/professional and vertically centre the "Use my current location" button text with respect to the button icon.
I've made a separate string resource for the hint instead of modifying the old resource because it was being used in search screen and the new resource was not suitable for use there.
Before
After
=> feat: tweak the search location screen's layout

app/src/main/res/layout/content_event.xml
Fixes #494 
Changes: Made the progress bar in event details centered.
=> fix: progress bar in event details not in center.

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
Fixes #1059 
Changes: 
Now the progress bar is not shown when incomplete information is submitted in attendees fragment.
=> fix: Progress bar hidden on incomplete information submission

app/src/playStore/java/org/fossasia/openevent/general/search/SmartAuthViewModel.kt
Fixes #1066 
Changes: Earlier, rotating the device would cause multiple popups to be shown if the user didn't dismiss the earlier ones. This was because the popup was shown whenever onStart() of the LoginFragment was called. But onStart() is called everytime on device rotation, leading to this bug.
Now, a boolean tracks whether the popup has been shown before.
There is no visual difference. The popups used to overlap each other completely, making it impossible to distinguish between them via screenshots.
=> fix: multiple popups in login screen on device rotation

app/src/fdroid/java/org/fossasia/openevent/general/search/GeoLocationViewModel.kt, app/src/fdroid/java/org/fossasia/openevent/general/search/LocationServiceImpl.kt, app/src/main/java/org/fossasia/openevent/general/WelcomeFragment.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/location/LocationExceptions.kt, app/src/main/java/org/fossasia/openevent/general/search/LocationService.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt, app/src/playStore/java/org/fossasia/openevent/general/search/GeoLocationViewModel.kt, app/src/playStore/java/org/fossasia/openevent/general/search/LocationServiceImpl.kt
Fixes #1072 
Changes: Earlier, `GeoLocationViewModel` contained code that directly used Android classes. This made it difficult to test.
I made `LocationService` interface to provide access to the administrative area and made two implementations of it: one for playstore and one for f-droid. The f-droid flavored implementation simply throws an exception on trying to get the administrative area.
The F-droid flavored `GeoLocationViewModel` simply hides the location option from the
user on initialization. The Playstore flavored `GeoLocationViewModel` works fully.
Made suitable changes to the Koin code.
Since `GeoLocationViewModel`'s new code doesn't require `Activity?`, it is no longer passed in
as a parameter in the `configure` method.
=> chore: remove direct uses of Android classes from GeoLocationViewModel

app/src/main/res/color/navigation_item.xml, app/src/main/res/layout/activity_main.xml
Fixes #1079
Changes: Earlier, all the tab titles were purple in color irrespective of whether
the tabs were active or not.
So, a color-list resource was made to rectify this.
Now, only the active tab's title is purple. Other's are grey(the same
color as the tab icons).
Current look:
Updated look:
=> feat: change bottom bar's inactive title color to grey

app/src/fdroid/java/org/fossasia/openevent/general/welcome/WelcomeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt, app/src/main/res/layout-land/fragment_welcome.xml, app/src/main/res/layout/fragment_welcome.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/playStore/java/org/fossasia/openevent/general/welcome/WelcomeViewModel.kt
Fixes #1073 
Changes: Earlier, there were two `ViewModel`s being used in `WelcomeFragment`.
In MVVM, a `View` is associated with only one `ViewModel`. To avoid duplication of logic, all distinct logic is split into smaller classes which can then be reused in different `ViewModel`s.
So now, `WelcomeFragment` has only one `ViewModel`(with two flavors: fdroid and playstore). Also, made a separate package for the welcome screen since its also a screen like others.
This is purely a refactoring. So, UI hasn't been changed in any way.
=> refactor: two ViewModels in the welcome screen into one ViewModel

app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserVM.kt
Fixes #930 
Changes: Disabled progress bar when coming back from ticketdetails. 
=> fix: Progress bar shows correctly in ordersUnderUserFragment

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt, app/src/main/res/layout/fragment_attendee.xml
Fixes #956 
Changes: Fixed bug where progressBar would show indefinitely if internet connection is lost in attendee fragment. Added snackbar when internet connection lost and when register button is pressed in attendeefragment. Moved isNetworkConnected to Utils. 
=> fix: attendeeframent progress bar

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt, app/src/main/res/layout/fragment_login.xml
Fixes #927 
Changes: Removed the dependency of login button on email verification. IMO the login button should always be enabled so as to show the exact error to the user, otherwise functions like
private fun hasErrors(email: String?, password: String?): Boolean {
if (email.isNullOrEmpty() || password.isNullOrEmpty()) {
mutableError.value = "Email or Password cannot be empty!"
return true
}
return false
}
are of no use.
=> fix: show error message on empty email password

app/src/main/res/layout/fragment_welcome.xml
Fixes #1124 
Changes: The "Use my current location" button's icon was too large which caused the whole layout to mess up.
This commit reverts the icon size to what it was originally.
Current layout:
Updated layout:
=> fix: Fix the welcome screen's portrait layout

app/src/main/java/org/fossasia/openevent/general/about/AboutEventViewModel.kt, app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt, app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt, app/src/main/java/org/fossasia/openevent/general/auth/SignUpViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt, app/src/main/java/org/fossasia/openevent/general/social/SocialLinksViewModel.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
Fixes #1127 
Changes: Earlier, configuration changes(like screen rotation) would trigger the last `SnackBar` to show up again. This was unfortunate as `SnackBar`s are used to represent transient things.
This was happening because `MutableLiveData` was being used instead of `SingleLiveEvent`.
Not all `ViewModel`s had this issue as some were already using `SingleLiveEvent`.
This commit fixes the issue.
=> fix: Rotating screen causes old snackbar to be shown again

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
Added alert dialog in edit user profile. The dialog appears when users try to change the data and click back button but don't click Update button first. The dialog confirms whether users want to discard or save changes.
Fixes #1133 
GIF:
=> feat: Added alert dialog when click back button in edit user info fragment

app/src/main/res/layout/content_event.xml, app/src/main/res/layout/item_card_events.xml, app/src/main/res/layout/item_card_similar_events.xml
Fixes #1135 
Changes: The `ImageView`s in `item_card_events.xml`, `item_card_similar_events.xml` and `content_event.xml` that display event images have width/height ratio of 2:1 which is the same as that of the images they display.
Earlier, since the ratios of `ImageView`s and images were different, the images were clipped. This was clearly noticeable on some images.
This change involved converting those layouts to `ConstraintLayout` because `ConstraintLayout` allows setting ratios.
=> feat: make ImageView aspect ratios same as that of source images

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/res/layout/fragment_events.xml
Fixes #1150 
Changes:
I checked if the view is already initialized. If it is, I reuse the view of search result, not reload the whole thing again. I also realized that the events fragment have the same problem so I make the same change
=> fix: After coming back from result detail, search result come back to the top, not current position #1150

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Fixes #1137 
When the EventDetailFragment comes back from AboutFragment, the text doesn't count the line because it has to render the text view first. So that's why "See more" button disappear, I changed it by using post method on the text view. It will start to check for lines of text to see whether to display "See more" or not only after rendering the text view
I made this change in the #1140 pull request but I screwed in branching and using Git so I close that pull request and make new one here. Sorry for the inconvienience, I'm still new and learning to make pull request properly
=> fix: "See more" button disappear #1337

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/res/layout/fragment_events.xml
Fixes #1192
Changes: 
Now, the message "Sorry, there are no events available" would not be displayed while events are being loaded.
=> fix: Hide no events available text when events are being loaded

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/res/layout/content_event.xml, app/src/main/res/values/strings.xml
Detail: I check for the number of line in the details of the event organizer, and then decide whether to set the "See more" of eventOrganizerDescription visibility. I add a click listener to toggle the text view of eventOrganizerDescription to show more/less information
Fixes #1202 
=> feat: Add toggle feature to see more organizer detail in EventDetailsFragment

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
Fixes #1217 
Changes: Refactored "OrdersUnderUserVM.kt" to "OrdersUnderUserViewModel.kt"
Now it makes perfect sense and easier to understand.
=> fix: Refactor class name

app/build.gradle, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/res/navigation/navigation_graph.xml
Fixes #1198 
Changes: Migrates the EventDetailsFragment to use Safe args instead of working with raw bundles. Arguments have been added to the navigation graph XML file, along with a more idiomatic Kotlin approach to creating argument bundles for related fragments. The delegate function navArgs has been used to retrieve the arguments for this fragment
=> refactor: Migrate EventDetailsFragment to use SafeArgs

app/src/main/res/layout/content_event.xml
Fixes #1243 
Changes: 
Changed default visibility of organizer name to 'gone'. When the organizer name exists, then it would be handled:
https://github.com/fossasia/open-event-android/blob/a5d757ede19037c5bbf419f6f8806454935591de/app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt#L157
=> fix: Hide organizer name when empty

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
Fixes #1260 
Changes:
isNullOrEmpty() only check if the length of string is zero or string null, while isNullOrBlank() check if the string is null or contains all empty spaces as well.
=> fix: detail name empty with spaces still valid

app/src/main/res/layout/item_card_order.xml
Details:
Remove unnecessary margin_bottom
Fixes #1261 
=> fix: fully display number of tickets TextView

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
Details:
I checked if the EditText already contains text -> if it is then it shouldn't reset the text when rotating
Fixes #652 
=> fix: edit text retention in EditProfileFragment

app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
Details:
There is a problem in the FavoriteFragment: The way it updates the favorite event list is wrong. Basically, when an event is clicked on the favorite icon, it is not removed from the adapter events' list. But as we call `favoriteEventViewModel.setFavorite(event.id, false)`, it is removed by the viewModel. And then the viewModel.events change so it notifies the code below inside FavoriteFragment:
```
favoriteEventViewModel.events
.nonNull()
.observe(this, Observer {
favoriteEventsRecyclerAdapter.addAll(it)
favoriteEventsRecyclerAdapter.notifyDataSetChanged()
showEmptyMessage(favoriteEventsRecyclerAdapter.itemCount)
Timber.d("Fetched events of size %s", favoriteEventsRecyclerAdapter.itemCount)
})
```
As the result, the whole event list is fetched again.
I fixed this by making sure …
=> feat: Add remove favorite event animation

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
Details:
I add tags on loading events (RELOADING OR INITIAL LOADING). The events' list is only loaded again if the tag is RELOADING or INITIAL LOADING + the event list is not loaded before.
Fixes #1295 
=> fix: Stop reloading events after rotating screen

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt
Fixes Issue #1304. The snackbar for permission to access external storage is now shown only once after granting the permission and not any time after that while changing profile photo. This has been done by checking the permission status beforehand
Changes: 
`permissionGranted = (ContextCompat.checkSelfPermission(requireContext(),
Manifest.permission.READ_EXTERNAL_STORAGE) == PackageManager.PERMISSION_GRANTED)
`
The variable permissionGranted has been initialized to the status of the permission rather than checking it at the time of clicking the profile picture and subsequently displaying the permission snackbar.
=> fix: display storage permission snackbar only once in EditProfileFragment

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/res/values-vi/strings.xml, app/src/main/res/values/strings.xml
Details:
Ticket Details Visibility is subscribed to the View Model as a boolean so that it survives after screen rotation
Fixes #1286 
=> fix: Retain ticket details' visibility after screen rotation

app/build.gradle, app/src/main/res/values/strings.xml
Fixes #1323 
Changes: 
1) Changed Room dependency version from version "2.1.0-alpha05"
to version "2.1.0-alpha04" 
2) Also changed single quotes ' ' to double quotes " " for consistency with other version variables.
EDIT:- Changes made on second commit after Travis build failed on first commit
3) Added the `translatable = "false"` property to strings that do not have their translations yet so that the Travis build succeeds. When all of their translations have been added, this property can be removed.
The build is now successful
=> fix: room dependency causing build fail

app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt, app/src/main/res/layout-land/item_card_order_details.xml, app/src/main/res/layout/item_card_order_details.xml
Fixes #1308 
Changes: hide organizer label when there is no information about the organizer
=> fix: Empty organizer section in Ticket Details (#1308)

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/res/layout/content_event.xml
Fixes #1281 
Add ?selectableItemBackground for making Visual Difference on Clicking them
=> fix: No Visual Difference on Clicking Views

app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
Details:
If there are already search results, they are reused, and the search query is not called again in the view model
Fixes #1347
=> fix: Retain search results after rotating screens

app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/res/layout/fragment_search_results.xml
Fixes #1339 
Changes:
The no internet layout used in EventsFragment has now been added to the SearchResultsFragment also making the UI more consistent. This new layout replaces the previously used TextView
=> feat: improve no internet layout for SearchResultsFragment

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt
Details:
When the screen is rotated, if a new image is chosen, the URI of that image is saved on onSaveInstanceState and then reload when the view is created after rotating
Fixes #1016 (The part where EditText is not retained in 1016 issue is already resolved in other PR and merged)
=> fix: stop reloading old image when rotating on EditProfileFragment

app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
**Details:**
Add a String to store the last search so that if a new search come, it reloads events again
Fixes #1349
**Screenshots for the change:**
Search works again, doesn't need to swipe down to reload
When rotating screen, the events are still retained
=> fix: making search in EventsFragment works again

app/src/main/java/org/fossasia/openevent/general/about/AboutEventFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt, app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
Fixes #1326 
Changes: Change every fragment in the app that uses LiveData in some capacity to use the `viewLifecycleOwner` property wherever it seems appropriate. To decide where it makes sense to change the Lifecycle owner in a live data subscription, I looked at what actions are being invoked in the observer. If they are purely UI related events, I have changed it to `viewLifecycleOwner`.
* I have tried to make as little changes as possible. Wherever a LiveData object was being observed solely for the purpose of controlling UI events (Snackbars, errors, etc), I have changed the Observer to use the fragment's view lifecycle instead.
* I have tested the app after each commit to ensure nothing is being broken because of these changes.
* In some places where UI events were being controlled …
=> refactor: Migrate project to use viewLifecycleOwner in fragments to observe livedata wherever it makes sense 

app/src/main/res/values/strings.xml
Fixes #1329 
Changes: 
PR #1324 was merged as it was a required PR but it had some additional unwanted changes which were made so that the Travis build passes. This PR aims to revert these changes and check the status of Travis build
Removed the `translatable = "false"` property from strings
=> chore: revert requested string changes

app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt
Fixes #1376 
Changes: Add LinearSnapHelper to the recycler view
=> feat: Add LinearSnapHelper to OrderDetailsFragment to enable snapping of tickets on the screen

app/build.gradle
Fixes #1242 
Changes: Updated navigation architecture components. This was caused by a bug in the api used. Check these links:
https://issuetracker.google.com/issues/128531879
https://developer.android.com/jetpack/androidx/releases/navigation
=> fix: App crash on switching between login and signup fragments

app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt
Fixes #1384. 
The emptyview is now displayed when the list becomes empty due to removal of all the favorite events
Changes:
The size of the list being used to determine if emptyview is to be displayed has been changed from using 
the size of A to size of B. 
- A is the `favoriteEventsRecyclerAdapter.itemCount`
- B is the new list of events obtained by observing on `favoriteEventViewModel.events`
Old code:
`favoriteEventsRecyclerAdapter.submitList(list)
showEmptyMessage(favoriteEventsRecyclerAdapter.itemCount)`
On using `submitList`, the list is asynchronously updated and hence in the next line, the `itemCount` obtained is the old not yet updated item count. Therefore I have replaced `favoriteEventsRecyclerAdapter.itemCount` with `list.size` where list is the parameter from observing on …
=> fix: display emptyview in FavoriteFragment when list is empty

app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/res/values/strings.xml
fixes Issue #1282 by displaying a snackbar message when a liked event is removed.
The snackbar also has an Undo option which undos the remove operation and the event is displayed again in the RecyclerView
Changes: 
Display snackbar message that liked event has been removed
The snackbar has an undo action button which can undo the remove operation
Also fixed 2 grammatical errors in strings.xml
=>  feat: display snackbar with undo action on removing liked event

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
Fixes: #1341
Changes:
1) EventsFragment in onCreateView, a check is made to display no internet card only if pre loaded events are not present and internet is not available
2) The boolean argument for showNoInternetScreen has been flipped for consistency i.e. when the argument is true, then NoInternet screen is displayed
=> fix: show previously loaded events on rotation + internet loss

app/src/main/res/layout/activity_main.xml
Details:
Setting the background on BottomNavigationView will make the ripple effect disappear.
Reference: https://stackoverflow.com/questions/40316411/bottomnavigationview-shadow-and-ripple-effect
Fixes #1392
=> feat: Add ripple effect on item when clicking on bottom navigation

app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTimeFragment.kt, app/src/main/res/navigation/navigation_graph.xml
Fixes: #1383
Changes: 
- A default value of 'null' has been assigned to the argument 'saved_date'.
- This resolves the crash as the SearchFragmentArgs generated files throws an IllegalArgumentException if this argument
does not exist in the bundle with which it is initialised in its 'fromBundle' method. Now a null value is passed and hence the crash
does not occur.
- Additionally 2 hardcoded strings have been replaced with their resource reference equivalents
The code in SearchFragmentArgs that was throwing the exception is : 
`if (bundle.containsKey("@string/saved_date")) {`
`// code that inserts it in arguments, redacted for simplicity`
`} else {`
`throw new IllegalArgumentException("Required argument \"@string/saved_date\" is missing and` `does not have an android:defaultValue");`
`}` …
=> fix: app crash due to IllegalArgumentException in SearchFragment

app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/res/layout/fragment_orders_under_user.xml, app/src/main/res/layout/item_card_favorite_event.xml
Fixes: #1397
Layout margins and card elevations have been adjusted for consistency between EventsFragment, OrdersUnderUserFragment and FavoriteFragment
View divider has been removed from FavoriteRecyclerView
=> feat: improve favorite events layout for consistency

app/src/main/res/xml/settings.xml
Fixes #1416 
Changes: Removed unnecessary white spaces.
Before
After
=> fix: Improved UI in Settings

app/src/main/res/layout/fragment_search_time.xml
Fixes: #1396
Changes:
Paddings have been increased, text color changed to black, layout background set to white so that the fade out animation
looks better, ripple effect added to CheckedTextView and some other changes
Old Layout:
New Layout:
=> feat: improve layout of SearchTimeFragment

app/src/main/res/layout/item_card_similar_events.xml
Summary Change: Set default image for similar events card
Fixes #1438
Before                                                                             
After
=> fix: Set default image for similar event card

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt, app/src/main/res/layout/fragment_orders_under_user.xml
Details:
- In the MainActivity, bottom navigation callback on actionReselectedListener is called to handle scroll link to the top of the current fragment (EventsFragment and OrdersUnderUserFragment)
Fixes #1387 
=> feat: Navigation icon clicked scroll to top

app/src/main/res/layout/fragment_attendee.xml
Fixes: #1458. 
Changes:
- Sets the layout_gravity to center_vertical of checkbox and textview in fragment_attendee.xml
- Removes following properties for Checkbox `layout_gravity="center"` and `gravity="center"` as `layout_gravity="center_vertical"` achieves what is required.
=> fix: misaligned terms conditions textview

app/src/main/res/layout/fragment_attendee.xml, app/src/main/res/layout/fragment_event.xml, app/src/main/res/layout/fragment_tickets.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Fixes #1020 
Changes: 
- Modified "register" buttons in fragment_attendee and fragment_tickets to Material Buttons 
and then applying rounded corners.
- Changed CardView of Tickets button in fragment_event to MaterialButton
=> fix: make register buttons corners rounded

app/src/main/res/layout/fragment_login.xml, app/src/main/res/layout/fragment_signup.xml, app/src/main/res/values/styles.xml
Fixes #1465 
Changes: Currently the Buttons in Login/Signup Page looks colored.
But it should appear enabled only when proper email and password is entered.
Changing Button to Material Button and applying it's styles seems to do the job.
Newer Look:
Before Typing :
After Typing:
=> fix: Changed Button to Material Button in Login/Signup Page

app/src/main/java/org/fossasia/openevent/general/common/RecyclerViewCallbacks.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/res/layout/content_event.xml
Fixes: #1475
Changes:
This reverts commit f2b9ae17f1072cbe6270dc3669fec7c7aca9aaea (PR #1443) which was causing multiple crashes including
- Crash on clicking event in EventsFragment after navigating from some other fragment
- EventsFragment being created and displayed briefly on selecting FavoriteFragment before displaying the intended fragment (i.e. FavoriteFragment)
- EventsFragment being created twice on selecting it from navigation
- Crash on searching for events in SearchFragment
- App hangs and sometimes crashes in FavoriteFragment on selecting a favorite event
Crashes before reverting:
After reverting:
Also
Fixes: #1480
Fixes: #1481
=> fix: multiple app crashes by reverting #1443

app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt, app/src/main/res/values/strings.xml
Fixes #1454 
Changes: 
- add check for required fields for empty (email, password, confirm password) before perform signup() ( **to prevent crash**)
- providing informed message to in required fields if fields were empty (for UX)
- change `equals()` to `==` for better readability
=> fix: empty field signup crash

app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsViewModel.kt
Fixes: #1474
Changes:
- On selecting a similar event from the EventDetailsFragment, a newEventDetailsFragment is created for the selected event.
- However using Koin DI, the same adapter object was being used.
- This resulted in app crashes on going back from the new event.
- This commit fixes the issue by instantiating the SimilarEventsListAdapter using its constructor and not KOIN DI
Additional Changes
- Removed shuffling of list of Similar events so that the fragment returns to the original order on pressing back
- Corrected a typo in the word 'similar' in `SimilarEventsViewModel`
=> fix: app crash on going back from similar fragment'

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/res/values-land/integers.xml, app/src/main/res/values-sw600dp-land/integers.xml, app/src/main/res/values-sw600dp/dimens.xml, app/src/main/res/values-sw600dp/integers.xml, app/src/main/res/values/integers.xml
Fixes: #1476
Changes:
- Displays multiple columns of events in EventsFragment by using GridLayoutManager instead of LinearLayoutManager
- The column count for events has been specified in newly created integers resources file for different source sets:
'landscape', 'smallest width 600 dp' and 'smallest width 600 dp landscape'
- Dimensions file for tablets created to increase size of a margin dimension
Previous Layout:
New Layout: 
Mobile landscape
Tablet Portrait
Tablet Landscape:
=> feat: display multiple columns of events in landscape and tablets

app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
Fixes: #1476
Changes:
On binding the EventViewHolder, the image resource is first set to the placeholder image.
This prevents an incorrect image to be displayed i.e. an image which was loaded for the previously loaded event
before this viewholder got recycled
=> fix: incorrect image displayed for event in EventsFragment

app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt
Fixes #1486 
Changes: Made items not shuffle on adding to favorites and sharing.
=> fix: Stop shuffle on like and share

app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersViewHolder.kt, app/src/main/res/layout/content_no_tickets.xml, app/src/main/res/layout/fragment_orders_under_user.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Fixes #1478 
Changes: sorted tickets so that event with earliest start date time appears first. Greyed out pictures of events on tickets which have ended and set alpha to 0.5 for ended events.
=> feat: Sort tickets and grey out old tickets.

app/src/main/res/layout/fragment_edit_profile.xml
Fixes #1511
Capitalises words in EditTexts for names in the `EditProfileFragment`
=> fix: capitalised words in EditProfileFragment

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/res/menu/event_details.xml, app/src/main/res/values/strings.xml
Fixes: #1505
Changes:
- Added a menu option to EventDetailsFragment to navigate to the external event url for the event
- If the external URL is null, then the menu option is disabled
Additional details:
- The option has been titled 'Open External Event URL' to maintain consistency with the eventyay frontend e.g. check the option on the right side at https://eventyay.com/e/a1fcaa21/coc/
- Instead of removing the menu item if the URL is null, I have chosen to disable the option because removing the item requires calling `invalidateOptionsMenu()` which will force the menu options to be prepared once again. This resets the favorite icon status also hence the favorite icon will have to be set again. Hence to avoid this complexity I have simply disabled it. If …
=> feat: add external event url menu option in EventDetailsFragment

app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/res/layout/fragment_tickets.xml
Detail:
Add no internet card on Ticket Fragment and show it when there is no internet and no tickets retained in view model
Fixes: #1491
=> feat: Add no internet view on TicketsFragment

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/res/layout/content_event.xml
Fixes: #1499
Changes:
- Add right margins and change other attributes according to constraint layout to correct the issue of text being cut off
Additional changes:
- Refactored a few layout view identifiers to remove ambiguity
=> fix: event title being cut off in EventDetailsFragment

app/build.gradle
Fixes: #1142
Changes:
- Updated minSdkVersion to 21 from 16 as OkHttp no longer supports API levels less than 21
- Removed unnecessary checks for sdk version >=21
- Removed 'left' and 'right' and replaced them with 'start' and 'end' in layout files as left/right are not needed in API 21 and start/end are recommended due to their RTL support
=> chore: Raise minSdk to Lollipop

app/src/main/java/org/fossasia/openevent/general/about/AboutEventFragment.kt, app/src/main/res/drawable/scrim_shape.xml, app/src/main/res/layout/fragment_about_event.xml, app/src/main/res/values/dimens.xml
Details:
- Load event image into the view
- Set title bar to event name or "" when appBarLayout is collapsed or expanded
Fixes: #1488
=> fix: about event view on collapsing layout

app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/res/layout/fragment_search_results.xml
Fixes: #1537
Changes:
- Moved chip layout at top in the vertical LinearLayout in SearchResultsFragment
- Cleaned up chip code and modified it to better suit Kotlin style
- Replaced deprecated method resources.getColorStateList with another method
- Hidden 'no results found' view and recyclerview on switching between chips
=> fix: set chip layout position at top of SearchResultsFragment

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt, app/src/main/res/layout/fragment_edit_profile.xml, app/src/main/res/values/strings.xml
Fixes: #1532
Changes:
- Changed color of update button and profile photo FAB to secondary color by using app theme
- Refactored 'buttonUpdate' to 'updateButton' for consistency
- Moved a hardcoded string to string resources
=> fix: set secondary color to editprofile buttons 

app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/res/layout/fragment_search_results.xml
Details:
- Hide Chipgroup on displaying no internet card
- Rename id an of XML views.
Fixes #1543  
=> fix: Hide chip group when there is no internet

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt
Fixes: #1531
Changes:
- Removed google sign in features due to buggy implementation.
=> fix: Disable Google Credentials Sign In leading to crash

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Fixes #1554 
Changes: 
using `stripHtml()` to remove html tags before isNullOrEmpty
=> fix: remove html tags before isNullOrEmpty

app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt, app/src/main/res/layout/fragment_search_results.xml
Detail:
- A clickable flag inside SearchViewModel is used to check whether chip should be clickable or not.
- Change id name of chip in XML file
Fixes: #1544
When loading, those chips card are not clickable any more
=> fix: Make chip not clickable while fetching events

app/src/main/res/layout/fragment_edit_profile.xml
Fixes #1555 
**Cause**
Popping of soft keyboard makes a layout resize
**Changes:** 
- change layout params to wrap content
- apply fabsize = mini
=> fix(ui): random increase in size of Edit FAB

app/src/main/res/values/styles.xml
=> fix: Removed Bold Style in Button

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventService.kt, app/src/main/java/org/fossasia/openevent/general/event/types/EventType.kt, app/src/main/java/org/fossasia/openevent/general/event/types/EventTypesApi.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTypeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt, app/src/main/res/layout/event_type_list.xml, app/src/main/res/layout/fragment_search.xml, app/src/main/res/layout/fragment_search_type.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values/strings.xml
Fixes #1519 
Changes: Add filtering using event types
=> feat: add event types for search

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/openevent/general/common/RecyclerViewCallbacks.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt, app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsListAdapter.kt, app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/res/xml/file_provider.xml
Fixes: #1315 
Changes:
Share event details along with event image
Added file_provider.xml to use cache event image URI  to work with API 24+
Screenshot
PS: I used placeholder image as event image for a testing purpose.
=> feat: Share event details along with image

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTimeFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTimeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTypeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt, app/src/main/res/navigation/navigation_graph.xml
Fixes #1567 
Changes: Saved Time and event type to shared preferences
=> fix: retain value of time and type of event

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventService.kt, app/src/main/java/org/fossasia/openevent/general/event/location/EventLocation.kt, app/src/main/java/org/fossasia/openevent/general/event/location/EventLocationApi.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchLocationViewModel.kt, app/src/main/res/layout/fragment_search_location.xml, app/src/main/res/values/strings.xml
Fixes #1421 
Changes: Added Popular Location in search location fragment
=> feat: add Event Location

app/src/main/java/org/fossasia/openevent/general/event/types/EventType.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt, app/src/main/res/layout/fragment_search_results.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/styles.xml
Fixes #1561 
Changes: Added event types to result fragment chips
=> feat: add Event Types Chips

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Fixes #1596 
Changes: Default INR currency in case of no currency passed
=> fix: default currency in case of no currency

app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt
Fixes #1602 
Changes:
- stripHtml() to remove Html tags before putting text in intent
- remove redundant qualifiers
- !value.isEmpty() -> value.isNotEmpty()
=> fix: strip raw html evenr description before sharing

app/src/main/java/org/fossasia/openevent/general/connectivity/MutableConnectionLiveData.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt, app/src/main/res/values/strings.xml
Details:
- Use broadcast receiver to detect connectivity change
- Delete Retry button in no internet card as connectivity is auto-detected and reloading will be made automatically
- Set up live data boolean for connectivity in ViewModel
Fixes: #1550 
=> fix: Move network logic into ViewModel with Broadcast Receiver

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/2.json, app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/speakers/Speaker.kt, app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerApi.kt, app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerDao.kt, app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerService.kt, app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerWithEvent.kt, app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerWithEventDao.kt, app/src/main/res/layout/content_event.xml, app/src/main/res/layout/item_speaker.xml
Fixes #1604 
Changes:Added Speakers section in Event Details
[WIP]Add a speaker page
=> feat: Add Speakers Section

app/src/main/res/layout/content_event.xml
Fixes #1630
Changes: Removed empty space between organizer and speaker containers.
=> fix: Remove empty space.

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeService.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/EventService.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt
Fixes #1344
Changes: Earlier, ViewModels were building flask filter queries themselves and passing them to Services.
This was not good because this leaked the data retrieval logic into the ViewModels. Only the Services should be concerned with data retrieval and they should abstract out that logic.
This change moves the logic into Services where it belongs.
=> chore: Move flask filter logic from ViewModels to Services

app/build.gradle, app/proguard-rules.pro, app/src/main/java/org/fossasia/openevent/general/search/PlaceSuggestionViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/search/PlaceSuggestionsAdapter.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchLocationViewModel.kt, app/src/main/res/layout/fragment_events.xml, app/src/main/res/layout/fragment_search_location.xml, app/src/main/res/layout/item_place_suggestion.xml
Fixes #1529 
Changes:
- Add MapBox Java lib
- Make Popular Locations Hide when Place Suggestions come and Vice-versa
- Add debounce to place query newtwork request (to avoid unnecessary calls)
**F-droid**
**PlayStore**
=> feat: MapBox AutoComplete Places

app/src/main/java/org/fossasia/openevent/general/event/EventService.kt, app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/subtopic/EventSubTopicConverter.kt, app/src/main/java/org/fossasia/openevent/general/event/topic/EventTopicConverter.kt, app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/types/EventTypeConverter.kt
Fixes #1637 
Changes: Use jacksonObjectMapper instead of ObjectMapper(),Do not add chip view in favourtie view items,nested query fix for location events
=> fix query,use jacksonObjectMapper and view holder crash

app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt, app/src/main/res/drawable/ic_close.xml, app/src/main/res/drawable/ic_done.xml, app/src/main/res/drawable/ic_filter.xml, app/src/main/res/layout/fragment_search_filter.xml, app/src/main/res/menu/search_filter.xml, app/src/main/res/menu/search_results.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values/strings.xml
Fixes #1609
Changes:
- Add Filter Search fragment (Currently Added Free stuff filter only - working)
- Display Free events only after applying filter
- Notice **PGConf APAC** its PAID event. After applying filter. Its not shown in the list
=> feat: Add Free Stuff Filter

app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsListAdapter.kt
Details:
Added a click listener for navigating to search result fragment when clicking on hashtag in EventsFragment
Fixes: #1649 
=> feat: search on clicking hashtag

app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTypeAdapter.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt, app/src/main/res/layout/event_type_list.xml, app/src/main/res/layout/fragment_search_type.xml
Detail:
Make font smaller + Add checked drawable on checked type. I couldn't find way to call function setCheckedMarkDrawable on ListView as it updates the container, so it will be checked on wrong item when scrolling
Fixes: #1581
=> fix: Improve Search Type Layout

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt
Details:
- Clear last search variable so that events are fetched again in EventsViewModel
Fixes #1657
=> fix: Enable reloading when pulling in EventsFragment

app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt
Fixes #1653 
Changes: 
- calling `chipGroup.removeAllView/()` before adding chips
=> fix: Repeating HashTags

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventService.kt, app/src/main/java/org/fossasia/openevent/general/event/faq/EventFAQ.kt, app/src/main/java/org/fossasia/openevent/general/event/faq/EventFAQApi.kt, app/src/main/java/org/fossasia/openevent/general/event/faq/EventFAQFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/faq/EventFAQViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/faq/FAQRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/event/faq/FAQViewHolder.kt, app/src/main/res/layout/fragment_event_faq.xml, app/src/main/res/layout/item_faq.xml, app/src/main/res/menu/event_details.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values/strings.xml
Fixes #1619 
Changes: Added Event Faq's in About Event Fragment
=> feat: Add Event FAQs

app/src/main/java/org/fossasia/openevent/general/auth/UserId.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/EventService.kt, app/src/main/java/org/fossasia/openevent/general/event/feedback/Feedback.kt, app/src/main/java/org/fossasia/openevent/general/event/feedback/FeedbackApi.kt, app/src/main/res/layout/content_event.xml, app/src/main/res/layout/dialog_feedback.xml, app/src/main/res/values/strings.xml
Fixes #1633 
Changes: Added option to submit feedback
=> feat: Add submit feedbacks

app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt
Prevent making a lot of fragment on the back stack when filtering the search result
Details:
Pop the fragment back to SearchResult and then start making a new search again with filter included
Fixes: #1658 
=> fix: Prevent making a lot of fragment on backstack when filtering search result

app/build.gradle, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/res/navigation/navigation_graph.xml
Uses the kotlin version of the safe args plugin to
get rid of the builder pattern when creating the arguments object
for a destination.
Fixes #1612. 
Changes: Migrates the project to use the kotlin safe args plugin
=> refactor: Use Kotlin only safe args plugin

app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt
Detail:
There was a discussion between me and @theLimitBreaker on the use of search button. Currently, it is used to make the request for autosuggestion, which I find not really useful because from my experience: when I'm having a good internet connection, then the autosuggestion appear really well but if the connection is poor, then I'm blocked in that fragment and I cannot navigate to other fragment and use the app right the start
In my opinion, the search button is the indication for searching, so it should not confuse users with a different meaning, even with good intention.
Fixes: #1673
=> fix: Make search button possible

app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/res/layout/fragment_favorite.xml
Detail:
- In FavoriteFragment, make chips not clickable
- Make search possible by adding search type
Fixes: #1655
=> fix: Make chip not checkable and search possible

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/topic/SimilarEventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/social/SocialLinksFragment.kt
Fixes #1553 
Changes:
Change the targetView of SnackBar to `EventDetailsCoordinatorLayout` to show the snackMessage without Scrolling
=> fix: show ErrorSnackMessage in EventDetailsCoordinatorLayout

app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchLocationFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTimeFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchTypeFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt, app/src/main/res/drawable/ic_close.xml, app/src/main/res/drawable/ic_star_border.xml, app/src/main/res/drawable/ic_time.xml, app/src/main/res/layout/fragment_search_filter.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values/strings.xml
=> feat: Add Location,Type, time filters

app/src/main/java/org/fossasia/openevent/general/RotateBitmap.kt, app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt
Fixes #1270 
Changes: 
Created RotateBitmap.kt file to prevent image from rotation
In EditProfileViewModel, created avatarUpdated, encodedImage, updatedImageTemp variable to retain the image.
=> fix: Selected image get rotate in edit profile (#1270)

app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt
Change the QR code based on server.
I have tested so that even though the QR image mobile app is not the same as the QR image in the pdf file, the value given after scanning is still the same.
Fixes: #1706
=> fix: Change the QR value based on server

app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/order/QrCode.kt, app/src/main/res/layout-land/item_card_order_details.xml, app/src/main/res/layout/item_card_order_details.xml, app/src/main/res/layout/item_enlarged_qr.xml
Detail:
- Set up click listener to enlarge QR Image
- Increate brightness when clicking on QR Image.
Fixes: #1215
Somehow my screen recorder doesn't record the change in brightness. But it increases the brightness to maximum when dialog appear and return to current brightness when dismissing the dialog
=> feat: Add enlarged QR Image + Increase brightness

app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
Details:
- Save chip state inside ViewModel and retain its check state in onCreateView()
Fixes: #1598
=> fix: Retain chip state on screen rotation in SearchResultFragment

app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt, app/src/main/res/layout/fragment_profile.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/settings.xml
Fixes #1750 
For not logged in - 
</p>
For logged in -
</p>
=> feat: Update settings and profile fragment for non authenticated users

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/feedback/FeedbackRecyclerAdapter.kt, app/src/main/res/values/strings.xml
Detail:
- Add livedata object to observe new submitted feedback.
- Extract string + fix small bugs
Fixes: #1746 
=> fix: Updating feedback section after making new one

app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt, app/src/main/res/menu/search.xml
Detail:
- Retain search query in SearchFragment and require focus when making search on screen rotation
Fixes: #862
=> fix: Retain searchview state in SearchFragment

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/order/Order.kt
Detail:
- Set default value of the order to 0 instead of null. This helps to book for free events.
Fixes: #1621, #1728 
Even though the null amount problem is editted in the server with [#5869](https://github.com/fossasia/open-event-server/pull/5869), current Android app still get HTTP 422 UNPROCESSABLE ENTITY so I made this PR.
=> fix: Reset default value for order

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/notification/Notification.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationApi.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationFragment.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationService.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationViewModel.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationsViewHolder.kt, app/src/main/res/drawable/ic_notifications_none.xml, app/src/main/res/drawable/ic_notifications_white.xml, app/src/main/res/layout/fragment_notification.xml, app/src/main/res/layout/item_card_notification.xml, app/src/main/res/layout/placeholder_item_card_notification.xml, app/src/main/res/menu/events.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values-bn-rIN/strings.xml, app/src/main/res/values-hi-rIN/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values/strings.xml
Part of #1617 
Changes: fragment setup
=> feat: Notification Fragment

app/build.gradle, app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerViewModel.kt, app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorService.kt, app/src/main/java/org/fossasia/openevent/general/utils/extensions/RxExtensions.kt, app/src/playStore/java/org/fossasia/openevent/general/auth/SmartAuthViewModel.kt
=> chore: Bump spotless from 3.16.0 to 3.23.0 and fix the violations

app/src/main/java/org/fossasia/openevent/general/event/EventService.kt, app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
=> fix: Show only upcoming or ongoing events

app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt, app/src/main/java/org/fossasia/openevent/general/attendees/Attendee.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeDao.kt, app/src/main/java/org/fossasia/openevent/general/attendees/ListAttendeeIdConverter.kt, app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDao.kt, app/src/main/java/org/fossasia/openevent/general/event/EventService.kt, app/src/main/java/org/fossasia/openevent/general/order/Order.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderDao.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketIdConverter.kt, app/src/main/res/navigation/navigation_graph.xml
Detail:
- Retain the attendee list, order and event in the database after fetching. 
So with this PR, if there is internet connection, orders/events/attendees are fetched from the API and saved to the database, otherwise fetched from the database.
When the user logs out, all of the saved orders and attendees information will be deleted from the database.
Fixes: #1610
=> fix: Retain ticket locally when logged in

app/src/fdroid/java/org/fossasia/openevent/general/auth/SmartAuthViewModel.kt, app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/java/org/fossasia/openevent/general/auth/AuthApi.kt, app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt, app/src/main/java/org/fossasia/openevent/general/auth/AuthViewModel.kt, app/src/main/java/org/fossasia/openevent/general/auth/CheckEmailResponse.kt, app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_auth.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values/strings.xml, app/src/playStore/java/org/fossasia/openevent/general/auth/SmartAuthViewModel.kt
Fixes #1749
Fixes #1251 
Fixes #1762
</p>
=> feat: Change authentication process and remove navigation (#1749)

app/src/main/java/org/fossasia/openevent/general/common/RecyclerViewCallbacks.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsListAdapter.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/utils/DataBindingAdapters.kt, app/src/main/res/layout/content_event.xml, app/src/main/res/menu/search.xml
Fixes: #1686
- Add shared element transition between event detail and event list.
- Remove unused Scope file.
=> feat: Add shared element transition

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt, app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt
Detail:
- The cause of the memory leak is because of the adapter of RecyclerView. If the adapter lives any longer than the RecyclerView does, the adapter is going to hold a reference to the RecyclerView which should have already gone out of memory.
Further description: https://stackoverflow.com/questions/35520946/leak-canary-recyclerview-leaking-madapter. 
To be honest, I don't completely understand the problem and the memory leak in here, but this fix does really improve the app as it is faster in my device and leak canary doesn't find any leaks. So please correct me if there is anything wrong or give me further explanations.
Fixes: #1780
=> fix: Remove click listeners to remove memory leaks

app/src/main/java/org/fossasia/openevent/general/event/EventDao.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/EventService.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
Part of #1689 
Changes: change flowable similar events to single events.
=> fix: updated favourites on event navigation & continuous topic api calls

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Fixes: #1801
fix: app crashes on screen rotation in TicketsFragment by moving cancelRequest() method to onDestroyView
=> fix: app crashes on screen rotation in TicketsFragment

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/res/navigation/navigation_graph.xml
Detail:
- popBackstack() changed into navigating from from action pop backstack in navigation graph. This might be a problem from Navigation Component as both methods are pretty much the same but the latter one doesn't produce the crashes so this is just a workaround.
Please give an advice if a better solution can be made
Fixes: #1803
=> fix: crash on coming back from AuthFragment

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/utils/extensions/FragmentExt.kt
Detail:
- Only set shared element transition for API version >= 26
- Remove delay for loading image
Fixes: #1805
Fixes #1804
Discussion on #1799
=> fix: Fix shared element transition problems for older version

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Detail:
- Previously, loadEvent() only called only when there is internet connection. Now it is loaded immediately when rootView is created.
- Delete postpone on shared element transition as sometimes it takes time to load the cover image. It is better to just make the transition with the default image if the cover image is not loaded.
Fixes: #1798 #1805
@liveHarshit can you test this implementation to see if there is any problem with shared element transition with your device
=> fix: Load event detail UI immediately on EventDetailsFragment

app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
Details:
- Move setting up livedata observer in onCreateView. Initially, it was onCreate(), so when comming back from other fragment, it is not set up anymore
Fixes: #1819
=> fix: Make ticket options updatable

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketDao.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketService.kt, app/src/main/res/layout/fragment_attendee.xml, app/src/main/res/values/strings.xml
Detail:
- Set up text change listener to retain the Attendee information in the ViewModel so that it survives screen rotation.
- Move UI initialization function from ViewModel into Fragment
- Move variables about logic or information from Fragment from Fragment to ViewModel to survive screen rotation.
- Break up code in onCreateView to smaller function
- Remove redundant methods.
- Improve some wrong naming.
Fixes: #1755
**Screenshots for the change:**
=> fix: Improve AttendeesFragment

app/build.gradle
Details:
- This is due to a bug from jackson-module-kotlin that doesn't support Android < API 24. So dependency version is reduced from 2.9.9 to 2.9.6
Fixes: #1829
**Related**
Issue #1784 
https://github.com/FasterXML/jackson-module-kotlin/issues/218
=> fix: Avoid app crash on login API version <= 24

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt
Details:
- Set up interface for handle back press in some fragment
- Return to TicketsFragment when click back button from AuthFragment
Fixes: #1822
=> fix: Improve navigation with AuthFragment

app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt
Fixes #1818 
- Remove duplication
</p>
=> fix: Retain chip state and search results after re-selecting the chip

app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt, app/src/main/res/drawable/circle_shape.xml, app/src/main/res/layout/item_card_order_details.xml, app/src/main/res/values/strings.xml
=> feat: Update Check-in status in orders

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/res/layout/fragment_attendee.xml, app/src/main/res/values/strings.xml
Details:
- Add offline payment method details
- Only add available payment methods
Fixes: #1839
=> feat: Add offline payment methods

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/utils/StringUtils.kt, app/src/main/res/layout/fragment_attendee.xml, app/src/main/res/layout/item_attendee.xml, app/src/main/res/values/strings.xml
Details:
- Add checking required fields
- Add hint for required fields
Fixes: #1857
=> feat: Add checking required fields

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/6.json, app/src/main/java/org/fossasia/openevent/general/attendees/Attendee.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewHolder.kt, app/src/main/res/layout/item_card_order_details.xml, app/src/main/res/values/strings.xml
=> feat: Show date and time wise check-in

app/build.gradle, app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt, app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt
=> fix: Wrong event URL is being shared

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/res/layout/fragment_attendee.xml
=> fix: Progress in Attendee fragment

app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/SignUpViewModel.kt
Fixes #1870 
- According to the server implementation, password length should be 8 characters.
=> fix: Sign Up not working

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/utils/Utils.kt, app/src/main/res/layout/fragment_attendee.xml, app/src/main/res/values-bn-rIN/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values/strings.xml
Details:
- Set up more logically time display of event
- Remove card type selector as it doesn't matter that much. Stripe automatically determine card type based on card number provided
- Hide billing information for free tickets
- Show pop up message for "required fields should be filled"
- Remove confirm dialog on ordering ticket (based on Eventbrite)
Fixes #1885
=> fix: Improve AttendeeFragment

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/6.json, app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt, app/src/main/java/org/fossasia/openevent/general/event/Event.kt, app/src/main/java/org/fossasia/openevent/general/event/EventApi.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventService.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchFilterFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchViewModel.kt, app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallConverter.kt, app/src/main/res/layout/fragment_search_filter.xml, app/src/main/res/navigation/navigation_graph.xml
Details:
- Remove retaining checkbox state in ViewModel as Android automatically do it for Checkbox component
- Set up Call For Speakers filter
- Hide option menu Call For Speakers with events not containing speakers call.
Fixes: #1825
=> feat: Filter call for speakers event

app/src/main/java/org/fossasia/openevent/general/common/RecyclerViewCallbacks.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/res/navigation/navigation_graph.xml
Details:
- Shorter implementation of shared element transition
- Remove pop fragments in the stack (followed Eventbrite navigation). Initially, the crash was due to shared element transition with transition containing pop fragments in backstack (this is what I guess, from the log I couldn't really find out the real problem). I checked the implementation in Eventbrite and they don't pop fragment in backstack for this, so I remove unnecessary options on navigation
```
<action
android:id="@+id/action_order_completed_to_event_detail"
app:destination="@id/eventDetailsFragment"
app:popUpTo="@id/eventsFragment" // removed
app:popUpToInclusive="false" /> // removed
```
Fixes: #1895
=> fix: Avoid crash on OrderCompleted

app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt, app/src/main/res/layout/fragment_signup.xml
Details:
- Move hint from TextInputEditText to TextInputLayout due to an Android bug that create a crash
- Add check so that when clicking on Google Auth in LoginFragment, it doesn't redirect back to AuthFragment
Related issue:
https://stackoverflow.com/questions/45898228/android-attempt-to-invoke-virtual-method-void-android-view-view-getboundsonsc
Fixes: #1923 
Fixes #1920
=> fix: crash on sign up

app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt, app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt
=> fix: Revalidate profile from API

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt, app/src/main/res/layout/fragment_edit_profile.xml, app/src/main/res/values/strings.xml
Details:
- Add user details section
- Add updating user details
Fixes: #1928
=> feat: Add user details under editing section

app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt
Details:
- This is just a dirty fix. The cause of the issue is due to methods (onCreate(), onCreateView(),...) of the fragment in backstack is somehow called. Discussed in #1896 comments section. Please give me some advices on this, I think this could probably be due to navigation component or memory leak (just a guess, I don't know tbh) @iamareebjamal 
Fixes: #1896
=> fix: wrong title name in fragments

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
=> fix: Progress dialog is continued showing on error in attendee fragment

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/res/values/strings.xml
Details:
- Remove card type picker as this is a unnecessary component
- Add Stripe implementation to the flow of ordering ticket
Flow of ordering paid ticket with Stripe:
-> Create order -> Send token -> Charge order -> Confirm order
Fixes: #1830
=> feat: Implement Stripe and charging

app/src/main/java/org/fossasia/openevent/general/search/SearchResultsFragment.kt, app/src/main/res/drawable/ic_clear.xml, app/src/main/res/layout/fragment_search_results.xml
=> feat: Add search edit text in SearchResultFragment

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/7.json, app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/notification/Notification.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationApi.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationDao.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationFragment.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationService.kt, app/src/main/res/drawable/ic_circle.xml, app/src/main/res/layout/fragment_events.xml
Part of #1984 
- Store notifications into the database
- fix: Sort notifications on the basis of data instead of the message
- Compare and check for new notifications
</p>
=> feat: Check for new notifications

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/discount/DiscountApi.kt, app/src/main/java/org/fossasia/openevent/general/discount/DiscountCode.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketService.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt, app/src/main/res/layout/fragment_tickets.xml, app/src/main/res/layout/item_ticket.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values/strings.xml
=> feat: Implement option to apply discount codes

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
Fixes #2015 
Changes:
deleted onStop()
set rootView.swiperefresh.setOnRefreshListener(null) in onDestroyView()
=> fix: events refresh

app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt, app/src/main/res/layout/dialog_rate_us.xml, app/src/main/res/values/strings.xml
=> feat: Ask for rating on first order

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/7.json, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/notification/Notification.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationApi.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationDao.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationFragment.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationService.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationViewModel.kt, app/src/main/res/layout/fragment_notification.xml, app/src/main/res/values/strings.xml
=> feat: Update read status and apply filter for notifications

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketIdAndQtyWrapper.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt, app/src/main/res/layout/fragment_tickets.xml, app/src/main/res/layout/item_ticket.xml, app/src/main/res/layout/item_ticket_details.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Details:
- Add donation ticket + input section for getting donation
Fixes: #2033 
=> feat: Add donation ticket

app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt, app/src/main/res/layout/item_ticket.xml, app/src/main/res/values/strings.xml
Details:
- Add ticket description
- Add ticket start/end date
- Add see more/less section about the ticket
Fixes: #2030 
=> feat: Add ticket details

app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/utils/extensions/FragmentExt.kt
Details:
- Cause of the problem is because of the TransitionInflater imported in EventDetailsFragment is not compatible with AuthFragment. One use AndroidX and one use normal Android library
Fixes: #2029
=> fix: app crashes navigating to AuthFragment from EventDetailsFragment

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/java/org/fossasia/openevent/general/auth/AuthApi.kt, app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt, app/src/main/java/org/fossasia/openevent/general/auth/EmailVerificationResponse.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt, app/src/main/java/org/fossasia/openevent/general/auth/RequestEmailVerification.kt, app/src/main/java/org/fossasia/openevent/general/auth/Token.kt, app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt, app/src/main/res/values/strings.xml
=> feat: Verify email with app

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt
Details:
- When initializing an order, the order status used is "INITIALIZING", not "PENDING".
- Don't have to cancel order when time counter goes down as the server automatically hanndle it
Fixes: #2026
=> fix: wrong order status

app/build.gradle, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventApi.kt, app/src/main/java/org/fossasia/openevent/general/event/EventService.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsListAdapter.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/paging/EventsDataSource.kt, app/src/main/java/org/fossasia/openevent/general/event/paging/EventsDataSourceFactory.kt, app/src/main/res/layout/fragment_events.xml
Details:
- Add pagination for EventsFragment
- Remove unused methods and variables
- Fix layout to match pagination
Fixes #84
Fixes #1681 
=> feat: Add pagination

app/src/main/java/org/fossasia/openevent/general/order/OrderApi.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
Details:
- Hide discount code when there is no internet in TicketFragment
- Fix extra in querystring orderApi
- Fix crashes due to wrong way to handle retaining ticket number in TicketAdapter
Fixes: #2041
=> fix: app crashes in TicketsFragment

.travis.yml, README.md, app/build.gradle, build.gradle, scripts/prep-key.sh, scripts/update-apk.sh
- Part of #2038
- Fixes #658 
- simplify signing apk
=> chore: Simplify signing apk, update apk generation and README

app/src/fdroid/java/org/fossasia/openevent/general/search/location/GeoLocationViewModel.kt, app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationFragment.kt, app/src/main/java/org/fossasia/openevent/general/welcome/WelcomeFragment.kt, app/src/main/res/layout/fragment_auth.xml, app/src/main/res/navigation/navigation_graph.xml
Details:
- Change navigation from WelcomeFragment similar to eventbrite
- Show skip button only when safeArgs attribute state so
Fixes: #2063
=> fix: Show skip button when only needed

app/src/main/java/org/fossasia/openevent/general/order/ExpiredOrderFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrdersUnderUserViewModel.kt, app/src/main/res/layout/dialog_filter_order.xml, app/src/main/res/layout/fragment_expired_order.xml, app/src/main/res/layout/fragment_orders_under_user.xml, app/src/main/res/values/strings.xml
Details:
- Add filtering and sorting orders
Fixes: #2028
=> feat: Add filtering and sorting dialog

scripts/update-apk.sh
=> fix: Malformed name of aab file

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/7.json, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/ticket/Ticket.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketDao.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketPriceRange.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketService.kt, app/src/main/res/layout/content_event.xml, app/src/main/res/values/colors.xml
=> feat: Display ticket price range and revalidate tickets

app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/EventService.kt, app/src/main/java/org/fossasia/openevent/general/event/paging/SimilarEventsDataSource.kt, app/src/main/java/org/fossasia/openevent/general/event/paging/SimilarEventsDataSourceFactory.kt, app/src/main/java/org/fossasia/openevent/general/event/similarevent/SimilarEventsListAdapter.kt, app/src/main/java/org/fossasia/openevent/general/event/topic/EventTopicApi.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderCompletedViewModel.kt, app/src/main/res/layout/content_event.xml, app/src/main/res/layout/fragment_order_completed.xml
=> feat: Add paging for fetching similar events

app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt, app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt
=> fix: Password length in settings and profile fragment

app/build.gradle
=> chore: Use correct Mapbox Java SDK version

app/build.gradle, app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/java/org/fossasia/openevent/general/auth/AuthApi.kt, app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/RequestPasswordReset.kt, app/src/main/java/org/fossasia/openevent/general/auth/ResetPasswordResponse.kt, app/src/main/java/org/fossasia/openevent/general/auth/forgot/PasswordReset.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/utils/AppLinkData.kt, app/src/main/java/org/fossasia/openevent/general/utils/AppLinkUtils.kt, app/src/main/res/layout/dialog_reset_password.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/fossasia/openevent/general/AppLinkUtilsTest.kt, app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt
Fixes #2079
- Add robolectric library for the test implementation
- Remove unnecessary library and methods from event unit test
=> feat: Handle app link intent for password reset and add unit test

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/utils/AppLinkUtils.kt, app/src/main/java/org/fossasia/openevent/general/utils/HttpErrors.kt
=> fix: Display unauthorization error while loading events

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt, app/src/main/res/layout/fragment_edit_profile.xml, app/src/main/res/navigation/navigation_graph.xml
Details:
- Fix app crash on going to EditProfileFragment
- Add error and check on username emptyness
Fixes: #2107
=> fix: empty input username

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/8.json, app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt, app/src/main/java/org/fossasia/openevent/general/StartupViewModel.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/Event.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/settings/Settings.kt, app/src/main/java/org/fossasia/openevent/general/settings/SettingsApi.kt, app/src/main/java/org/fossasia/openevent/general/settings/SettingsDao.kt, app/src/main/java/org/fossasia/openevent/general/settings/SettingsService.kt, app/src/main/res/layout/fragment_attendee.xml
Fixes #2101 
Fixes #2083 
</p>
=> feat: Fetch settings and divide events view model

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt, app/src/main/res/layout/fragment_attendee.xml, app/src/main/res/layout/item_attendee.xml
Fixes #2121 
it was due to conflicts of same ids.
=> fix: Billing information from

app/build.gradle, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/res/layout/fragment_attendee.xml
=> feat: Add searchable spinner for country name

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeService.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/res/layout/item_attendee.xml, app/src/main/res/layout/item_card_order_details.xml, app/src/main/res/values/strings.xml
Details:
- Gender picker should be turned into a spinner instead of edit text
- Empty white unused space about event detail of order detail section
- Empty organizer name in Tickets Fragment
- Confusing Cancel/Continue Order
Subtotal/Total ticket price in AttendeeFragment
- Display button "Register", "Pay now"
- Fix filter for custom form
Fixes: #2126 
=> fix: Illogical information displayed in Ticket and Event section

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt, app/src/main/res/layout/fragment_attendee.xml, app/src/main/res/layout/item_ticket.xml
Details:
- Add quantity picker for donation ticket
- Fix UI
- Remove redundant methods
Fixes: #2086
=> feat: Add quantity picker for donation ticket

app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt, app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt, app/src/main/res/layout/fragment_edit_profile.xml, app/src/main/res/values/strings.xml
=> feat: Add more field to update user detail

app/build.gradle
Fixes #2141 
Reference issue: https://issuetracker.google.com/issues/137782949
Solution: https://issuetracker.google.com/issues/137268935
=> chore: Bump nav_version and set jvm target to 1.8

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketDetailsViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt, app/src/main/res/layout/item_ticket.xml, app/src/main/res/layout/item_ticket_details.xml
Fixes #2119 
- Set margin b/w ticket name and price
- Display tickets price with two decimal places
- Fix event time in tickets fragment
</p>
=> fix: Event time, price and UI for tickets

app/src/main/java/org/fossasia/openevent/general/auth/AuthApi.kt, app/src/main/java/org/fossasia/openevent/general/auth/AuthService.kt, app/src/main/java/org/fossasia/openevent/general/auth/LoginViewModel.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileFragment.kt, app/src/main/java/org/fossasia/openevent/general/auth/ProfileViewModel.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/topic/EventTopicApi.kt, app/src/main/java/org/fossasia/openevent/general/notification/NotificationApi.kt, app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerApi.kt, app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerService.kt, app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorService.kt, app/src/main/res/layout/dialog_confirm_delete_account.xml, app/src/main/res/layout/dialog_delete_account.xml, app/src/main/res/layout/fragment_profile.xml, app/src/main/res/values/strings.xml
=> feat: Add delete account feature

app/build.gradle
Reverts fossasia/open-event-attendee-android#2157
Fixes #2159
=> Revert "chore(deps): bump jackson-module-kotlin from 2.9.6 to 2.10.0.pr1"

app/src/main/java/org/fossasia/openevent/general/MainActivity.kt, app/src/main/java/org/fossasia/openevent/general/di/HostSelectionInterceptor.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/settings/SettingsFragment.kt, app/src/main/java/org/fossasia/openevent/general/settings/SettingsViewModel.kt, app/src/main/res/layout/dialog_api_configuration.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/settings.xml
=> feat: Add server configuration field for fDroid

app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteEventsListAdapter.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchPagedListAdapter.kt, app/src/main/res/layout/fragment_favorite.xml, app/src/main/res/layout/item_card_favorite_event.xml
=> feat: Add date format for Favorite Event Fragment

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/8.json, app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt, app/src/main/java/org/fossasia/openevent/general/auth/AuthFragment.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventApi.kt, app/src/main/java/org/fossasia/openevent/general/event/EventService.kt, app/src/main/java/org/fossasia/openevent/general/sessions/Session.kt, app/src/main/java/org/fossasia/openevent/general/sessions/SessionApi.kt, app/src/main/java/org/fossasia/openevent/general/sessions/SessionService.kt, app/src/main/java/org/fossasia/openevent/general/speakercall/EditSpeakerFragment.kt, app/src/main/java/org/fossasia/openevent/general/speakercall/Proposal.kt, app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallFragment.kt, app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallProposalFragment.kt, app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallProposalViewModel.kt, app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallViewModel.kt, app/src/main/java/org/fossasia/openevent/general/speakers/ListSpeakerIdConverter.kt, app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerApi.kt, app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerId.kt, app/src/main/res/layout/fragment_speakers_call_proposal.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values/strings.xml
Details:
- Update UI for SpeakerCallProposalFragment to create/update proposal
- Setup ViewModel, Service to update/create simple proposal
Work for later (another issue and PRs): 
- Setup Custom Form + Add more Propsal fields
- Improve SpeakersCallFragment with merge RxJava
Fixes: #1880
=> feat: Add session for event

app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallFragment.kt, app/src/main/res/values/strings.xml
Details:
- Fetch new speaker profile/sessions after creating/updating speaker profiles/sessions
- Extract strings
Fixes: #2164 
=> fix: Update speakers and session

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/favorite/FavoriteFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/SearchFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/type/SearchTypeFragment.kt, app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt, app/src/main/java/org/fossasia/openevent/general/speakers/SpeakerFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/res/values/strings.xml
Details:
- Add string format
- Use Koitlin isVisible
Fixes: #2180
=> feat: Add string format

app/src/main/java/org/fossasia/openevent/general/about/AboutEventViewModel.kt, app/src/main/java/org/fossasia/openevent/general/auth/EditProfileViewModel.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderDetailsViewModel.kt
Details:
- Add chaining RxJava on loading order details, signing up, editting user profile
- Remove unused methods
Fixes: #2116
=> feat: Add chaining RxJava

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/search/type/SearchTypeFragment.kt, app/src/main/res/layout/content_event.xml, app/src/main/res/layout/fragment_event.xml, app/src/main/res/values/strings.xml
=> fix: Feedback - button and crashes

app/schemas/org.fossasia.openevent.general.OpenEventDatabase/9.json, app/src/main/java/org/fossasia/openevent/general/OpenEventDatabase.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/tax/Tax.kt, app/src/main/java/org/fossasia/openevent/general/event/tax/TaxApi.kt, app/src/main/java/org/fossasia/openevent/general/event/tax/TaxDao.kt, app/src/main/java/org/fossasia/openevent/general/event/tax/TaxService.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsRecyclerAdapter.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/utils/HttpErrors.kt, app/src/main/res/layout/fragment_attendee.xml, app/src/main/res/layout/item_ticket.xml, app/src/main/res/layout/item_ticket_details.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values/strings.xml
=> feat: Add tax for tickets

app/src/main/java/org/fossasia/openevent/general/event/EventUtils.kt, app/src/main/res/layout/content_event.xml, app/src/test/java/org/fossasia/openevent/general/event/EventUtilsTest.kt
=> fix: Date format and feedback button style

app/src/main/java/org/fossasia/openevent/general/discount/DiscountApi.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketService.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
=> fix: Apply new discount code routing

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
=> fix: Null check for ticket url 

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt, app/src/main/res/layout/fragment_attendee.xml, app/src/main/res/navigation/navigation_graph.xml
=> fix: Add checkbox for enabling billing information

app/src/fdroid/java/org/fossasia/openevent/general/search/location/LocationServiceImpl.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventsViewModel.kt, app/src/main/java/org/fossasia/openevent/general/search/location/SearchLocationViewModel.kt, app/src/main/res/values/strings.xml, app/src/playStore/java/org/fossasia/openevent/general/search/location/LocationServiceImpl.kt
=> fix: App crash when no location found

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Detail:
- When event doesn't contain any location details (latitude, longitude), imageMap is hide
Fixes: #2256
=> fix: Hide map when no information is present

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/order/Charge.kt, app/src/main/java/org/fossasia/openevent/general/utils/Error.kt, app/src/main/java/org/fossasia/openevent/general/utils/ErrorUtils.kt, app/src/main/java/org/fossasia/openevent/general/utils/HttpErrors.kt, app/src/main/java/org/fossasia/openevent/general/utils/StringUtils.kt
=> fix: Add error utils, fix stripe error message and charge data class

app/build.gradle, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt, app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallProposalFragment.kt, app/src/main/res/layout/content_event.xml, app/src/main/res/layout/fragment_session.xml, app/src/main/res/layout/fragment_speakers_call_proposal.xml
Details:
- Add slide up/down animation for View,TextView
Fixes: #2182
=> feat: Add slide up down animation

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values/strings.xml
=> fix: Handle unverified account error

app/src/main/java/org/fossasia/openevent/general/sessions/SessionFragment.kt, app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewHolder.kt, app/src/main/java/org/fossasia/openevent/general/sessions/SessionViewModel.kt, app/src/main/java/org/fossasia/openevent/general/speakercall/SpeakersCallFragment.kt, app/src/main/java/org/fossasia/openevent/general/sponsor/SponsorsDetailAdapter.kt, app/src/main/res/layout/fragment_speaker.xml, app/src/main/res/layout/fragment_speakers_call.xml, app/src/main/res/layout/item_session.xml, app/src/main/res/layout/item_sponsor_detail.xml, app/src/main/res/values/strings.xml
Detail:
- use isVisible() Kotlin function
- Fix some empty space in session card
- Strip HTML in Sponsor section
- Add auto link in Speakers Call announcement section
- Improve network call in Session Fragment
- Fix clickListener in Session Detail Section
Fixes: #2290
=> fix: Multiple small enhancements in Event Detail Fragment

app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/utils/Error.kt, app/src/main/java/org/fossasia/openevent/general/utils/ErrorUtils.kt
=> fix: Check unverified user with error source

app/build.gradle, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeViewModel.kt, app/src/main/java/org/fossasia/openevent/general/di/Modules.kt, app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt, app/src/main/java/org/fossasia/openevent/general/order/OrderService.kt, app/src/main/java/org/fossasia/openevent/general/paypal/Paypal.kt, app/src/main/java/org/fossasia/openevent/general/paypal/PaypalApi.kt, app/src/main/java/org/fossasia/openevent/general/paypal/PaypalPaymentResponse.kt, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsFragment.kt, app/src/main/res/values/strings.xml
Fixes #333
Fixes #1813
**Screenshots**
**Additional Context**
Waiting for https://github.com/fossasia/open-event-server/pull/6297 to be merged, another PR will be made and open to send verification to the server before confirming orders
=> feat: Add paypal

app/src/main/java/org/fossasia/openevent/general/auth/EditProfileFragment.kt, app/src/main/res/layout/fragment_edit_profile.xml
=> fix: Make name not mandatory and add progress dialog in edit profile

app/build.gradle, app/src/main/java/org/fossasia/openevent/general/attendees/AttendeeFragment.kt
Fixes #2341 
Fixes #2342 
Fixes #2343 
Changes: Bump the version of stripe-android from 10.4.3 to 11.0.5
=> chore: Bump stripe from 10.4.3 to 11.0.5 and fix errors

app/src/main/AndroidManifest.xml
Fixes #2292 
Changes: Changed the DEFAULT_BASE_URL for release build
<a href="https://imgflip.com/gif/3akg6p"><img src="https://i.imgflip.com/3akg6p.gif" title="made at imgflip.com"/></a>
=> fix: App link intent appear when clicking on Terms and Policy Section

app/src/main/java/org/fossasia/openevent/general/event/EventService.kt
Fixes #2183 
Changes: [**Before** - for removing favourite event it was passing  favoriteEventId so that it was showing error  "Object not found" 
**After** - In open-event-api-dev.herokuapp for deleteing a favourite event it is expecting event.id , So I change favouriteEventId to event.id And now it is able to remove favourite events successfully. ]
=> fix: Use event ID in favorite remove API call

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
Fixes #2357 
Changes: In EventsFragment, the notification dot visibility was directly dependent on the logged-in status of the user and also on the observer in the StartupViewModel. So, I have removed the code responsible for setting the visibility based on logged-in status. Now, the dot only appears when there is a new notification.
=> fix: Notification dot visibility logic

app/src/main/java/org/fossasia/openevent/general/event/EventDetailsFragment.kt
Fixes #2390 
Changes: 
Previously the visibility of the container layout was dependent on the size of the list fetched from the API. So, whenever the list reaches the end of the pagination, due to size 0, the visibility of the layout was set as GONE. Now, I have used a boolean hasSimiliarEvents (initially false) which get updated depending on the size of the list and container layout's visibility depends on this variable. So, even if there are events on any page the variable will be set as true otherwise false. This resolved the issue.
=> fix: Similar events collapsing

app/build.gradle, app/src/main/java/org/fossasia/openevent/general/ticket/TicketsViewModel.kt
=> chore(deps): bump com.diffplug.gradle.spotless from 3.25.0 to 3.26.0

app/build.gradle
Fixes #2426 
Changes: Remove useless native binaries from PayPal SDK
=> feat: Remove useless native binaries from paypal SDK (#2426)

app/src/main/res/layout/item_card_similar_events.xml
Fixes #2460 
Changes:  Instead of hard coding the fab size, wrap content is used.
=> fix: Fab size issue

scripts/update-apk.sh
=> fix: branch release for open-event-attendee

scripts/update-apk.sh
During the release process, metadata will not get 
uploaded if we are in apk directory
=> chore: cd to prev dir for fastlane metadata

app/src/main/java/org/fossasia/openevent/general/auth/SignUpFragment.kt, app/src/main/res/layout/fragment_signup.xml
Fixes #2507 
Changes: Fixed, added hideSoftKeyboard()
Keyboard is hidden by clicking anywhere on the screen.
=> fix: Hiding Keyboard on clicking anywhere on SignUp Fragment (#2507)

app/src/main/java/org/fossasia/openevent/general/event/EventsFragment.kt
Fixes #2480 
Changes: Instead of showing the message after the completion of the request, I am calling the show function after the recyclerview get populated.
=> fix: Resolve events UI bug

app/build.gradle, build.gradle
Fixes #2548 
Changes: Bump the version of com.diffplug.gradle.spotless from 3.26.1 to 3.27.0 and fix build errors
=> chore: bump com.diffplug.gradle.spotless from 3.26.1 to 3.27.0
